//! **The program that makes a nife boot stick** (DECISIONS §157, amended 2026-09-19).
//!
//! Name: provisional. Minted 2026-09-19 by the lane that built it
//! (`milestone/the-program-that-makes-the-stick`).
//! A noun for the thing a person downloads and what it makes: a stick. Considered and set aside
//! `installer` (DECISIONS §157's rung 2 installs nife onto a PC's own disk, and that is a different
//! program), `stick_writer` (a writer suggests a raw image written over the disk, which is the path
//! this program avoids in the common case), and `boot_stick` (names the product rather than the
//! program). calef names programs; expect this to change.
//!
//! One file per host operating system, downloaded and run, with every architecture's boot file
//! inside it. Run, it finds the USB sticks and SD cards on the machine, asks which, and writes the
//! boot files to it. The common case is a copy onto a stick that is already FAT32, which needs no
//! administrator rights and erases nothing; erasing is the fallback for a stick that is not.
//!
//! The halves:
//!
//! - [`disk`] is the host-independent model and **the one rule for what may be written**
//!   ([`disk::refusal`]), plus the choice between copying and erasing ([`disk::plan`]).
//! - `macos`, `linux` and `windows` each turn their host's description of its disks into
//!   [`disk::Disk`]s (each compiled only where it runs, and in tests), and hold the few commands that change a disk.
//! - [`payload`] is what is carried; [`mod@write`] puts it on a mounted volume safely.
//! - [`cli`] is the whole conversation with the person, tested against a fake host, and [`host`]
//!   is the thin half that runs each OS's own tools, proved on each OS instead.
//!
//! See notes/boot-stick.md for how it is built, tested, and what it has and has not run on.

pub mod cli;
pub mod disk;
pub mod host;
pub mod payload;
pub mod plist;
pub mod write;

#[cfg(any(target_os = "macos", test))]
pub mod macos;

#[cfg(any(target_os = "linux", all(test, unix)))]
pub mod linux;

pub mod windows;

/// The embedded boot files and the build label, generated by `build.rs`.
pub mod embedded {
    use crate::payload::File;
    include!(concat!(env!("OUT_DIR"), "/embedded.rs"));
}
