//! Device trees no firmware would write, and what the parser must do with them.
//!
//! **Every test here is a regression for a bug that was real.** The other two test files parse the
//! device trees QEMU actually hands us; this one is the inverse, and it exists because the blob is
//! the first thing this kernel reads and the last thing it can validate against anything else. The
//! pointer comes from firmware. There is no second opinion.
//!
//! Both bugs below came out of milestone 42's fuzzing leg
//! (`fuzz/fuzz_targets/device_tree_blob_walk`, 2026-08-02), and it is worth recording *how*,
//! because they came out differently:
//!
//!   * The deep-nesting index was found by **reading the code** while writing the fuzz target, and
//!     ten minutes of fuzzing did **not** rediscover it. Seventeen levels of nesting with a matching
//!     name at the bottom is structure a mutational fuzzer will not synthesize from a corpus of real
//!     device trees, which are three deep.
//!   * The `Region::end` overflow was found by **the fuzzer**, in about ten minutes, from a mutated
//!     copy of the committed `qemu-aarch64-virt.dtb`. Nobody had thought to look at it.
//!
//! That is the argument for having both, stated as evidence rather than as a slogan. See
//! notes/fuzzing.md.
//!
//! These run on the host in milliseconds, so the inputs that cost real time to find cost nothing to
//! keep.

use device_tree_blob::{DeviceTreeBlob, Error, Region};

/// Enough of a device tree to reach the structure block, built from parts.
///
/// The header is 40 bytes of big-endian u32s, then the memory-reservation block (one all-zero entry
/// terminates it), then the structure block, then the strings block. Hand-assembled rather than
/// generated by `dtc`, because the whole point is to write blobs `dtc` would refuse.
struct Blob {
    strings: Vec<u8>,
    structure: Vec<u8>,
}

impl Blob {
    fn new() -> Blob {
        Blob {
            strings: Vec::new(),
            structure: Vec::new(),
        }
    }

    /// Intern a property name and return its offset in the strings block.
    fn string(&mut self, s: &[u8]) -> u32 {
        let at = self.strings.len() as u32;
        self.strings.extend_from_slice(s);
        self.strings.push(0);
        at
    }

    fn token(&mut self, t: u32) -> &mut Self {
        self.structure.extend_from_slice(&t.to_be_bytes());
        self
    }

    /// `FDT_BEGIN_NODE` plus the node's name, NUL-terminated and padded to four bytes.
    fn begin_node(&mut self, name: &[u8]) -> &mut Self {
        self.token(1);
        self.structure.extend_from_slice(name);
        self.structure.push(0);
        while !self.structure.len().is_multiple_of(4) {
            self.structure.push(0);
        }
        self
    }

    fn end_node(&mut self) -> &mut Self {
        self.token(2)
    }

    /// `FDT_PROP`: a length, a name offset, then the value padded to four bytes.
    fn prop(&mut self, name: &[u8], value: &[u8]) -> &mut Self {
        let name_off = self.string(name);
        self.token(3);
        self.structure
            .extend_from_slice(&(value.len() as u32).to_be_bytes());
        self.structure.extend_from_slice(&name_off.to_be_bytes());
        self.structure.extend_from_slice(value);
        while !self.structure.len().is_multiple_of(4) {
            self.structure.push(0);
        }
        self
    }

    fn finish(&mut self) -> Vec<u8> {
        self.finish_with_reservations(&[])
    }

    /// Like [`finish`](Self::finish), with real `/memreserve/` entries ahead of the terminating
    /// all-zero pair. The fixtures' reservation blocks are empty, so this is the only way a test
    /// gets a non-trivial one.
    fn finish_with_reservations(&mut self, rsv: &[(u64, u64)]) -> Vec<u8> {
        self.token(9); // FDT_END

        const HEADER: usize = 40;
        let off_rsvmap = HEADER;
        let off_struct = off_rsvmap + 16 * (rsv.len() + 1); // the all-zero entry terminates the list
        let off_strings = off_struct + self.structure.len();
        let total = off_strings + self.strings.len();

        let mut b = Vec::with_capacity(total);
        for word in [
            0xd00d_feed,
            total as u32,
            off_struct as u32,
            off_strings as u32,
            off_rsvmap as u32,
            17, // version
            16, // last_comp_version
            0,  // boot_cpuid_phys
            self.strings.len() as u32,
            self.structure.len() as u32,
        ] {
            b.extend_from_slice(&word.to_be_bytes());
        }
        for &(start, size) in rsv {
            b.extend_from_slice(&start.to_be_bytes());
            b.extend_from_slice(&size.to_be_bytes());
        }
        b.extend_from_slice(&[0u8; 16]);
        b.extend_from_slice(&self.structure);
        b.extend_from_slice(&self.strings);
        b
    }
}

/// Two big-endian 64-bit cells: the `#address-cells = 2, #size-cells = 2` layout every 64-bit board
/// uses, which is what the fixtures carry and what `decode_reg` sees in practice.
fn reg64(start: u64, size: u64) -> Vec<u8> {
    let mut v = Vec::new();
    v.extend_from_slice(&start.to_be_bytes());
    v.extend_from_slice(&size.to_be_bytes());
    v
}

/// A tree `depth` levels deep whose deepest node is the only one matching `intc`, and which carries
/// a `reg` there. Depth 1 is the root, so `depth = 17` puts the interesting node at 17.
fn nested(depth: usize) -> Vec<u8> {
    let mut b = Blob::new();
    b.begin_node(b"");
    b.prop(b"#address-cells", &2u32.to_be_bytes());
    b.prop(b"#size-cells", &2u32.to_be_bytes());
    for _ in 0..depth - 2 {
        b.begin_node(b"bus");
    }
    b.begin_node(b"intc@8000000");
    b.prop(b"reg", &reg64(0x800_0000, 0x1_0000));
    for _ in 0..depth {
        b.end_node();
    }
    b.finish()
}

/// **A node nested past the cell stack must not be indexed for.**
///
/// `node_reg` carries `#address-cells`/`#size-cells` down a 16-entry per-depth array, and used to
/// match a node at *any* depth >= 2. At depth 17 the `reg` arm read `acells[depth - 1]`, which is
/// `acells[16]` on a 16-element array: an out-of-bounds index, i.e. a panic, in the parser the
/// kernel runs against a blob it did not write, before there is any way to report a failure.
///
/// The fix refuses to match past the stack rather than clamping the index, so the answer is "no such
/// node" (`Ok(0)`) instead of a region decoded with cell widths this walk stopped tracking.
#[test]
fn a_node_deeper_than_the_cell_stack_is_not_found_rather_than_indexed() {
    let mut out = [Region { start: 0, size: 0 }; 4];

    // Inside the stack: found, and decoded with the root's 2/2 cells.
    let shallow = nested(3);
    let dtb = DeviceTreeBlob::from_bytes(&shallow).unwrap();
    assert_eq!(dtb.node_reg(b"intc", &mut out).unwrap(), 1);
    assert_eq!(
        out[0],
        Region {
            start: 0x800_0000,
            size: 0x1_0000
        }
    );

    // Past it: not found. The assertion that matters is that this returns at all.
    for depth in [16, 17, 24, 40] {
        let deep = nested(depth);
        let dtb = DeviceTreeBlob::from_bytes(&deep).unwrap();
        assert_eq!(
            dtb.node_reg(b"intc", &mut out).unwrap(),
            0,
            "a node at depth {depth} should be reported as absent, not indexed for"
        );
        // The sibling lookups walk the same tree with the same per-depth arrays.
        assert!(dtb.node_reg_compatible(b"arm,pl031", &mut out).is_ok());
        assert!(dtb.node_prop(b"intc", b"reg").is_ok());
    }
}

/// **A `reg` pair whose `start + size` wraps is refused, not passed out.**
///
/// Found by the fuzzer. `Region::end()` was a plain `start + size` on two numbers straight out of the
/// blob, and `kernel/src/memory.rs`'s `place_bitmap` calls it on every RAM region the device tree
/// declares. Under the dev profile's overflow checks (which the kernel's own test builds use) that is
/// a panic on the boot path.
#[test]
fn a_memory_region_that_wraps_the_address_space_is_refused() {
    let mut b = Blob::new();
    b.begin_node(b"");
    b.prop(b"#address-cells", &2u32.to_be_bytes());
    b.prop(b"#size-cells", &2u32.to_be_bytes());
    b.begin_node(b"memory@0");
    b.prop(b"reg", &reg64(u64::MAX, u64::MAX));
    b.end_node();
    b.end_node();
    let blob = b.finish();

    let dtb = DeviceTreeBlob::from_bytes(&blob).unwrap();
    let mut out = [Region { start: 0, size: 0 }; 4];
    assert_eq!(
        dtb.memory_regions(&mut out),
        Err(Error::RegionOverflow),
        "a region past the top of the address space is not a region"
    );
}

/// **`Region::end` holds on its own**, whatever built the region.
///
/// The type is `pub` with `pub` fields, so the refusal above is not the only thing standing between
/// a hostile pair and the addition. Saturating is the backstop; the refusal is the check.
#[test]
fn region_end_saturates_rather_than_wrapping() {
    assert_eq!(
        Region {
            start: u64::MAX,
            size: 1
        }
        .end(),
        u64::MAX
    );
    assert_eq!(
        Region {
            start: u64::MAX,
            size: u64::MAX
        }
        .end(),
        u64::MAX
    );
    // The ordinary case is unchanged.
    assert_eq!(
        Region {
            start: 0x4000_0000,
            size: 0x800_0000
        }
        .end(),
        0x4800_0000
    );
}

// ================================================================================================
// Milestone 85: what the mutation run proved this file was not yet checking. Every test below
// kills named survivors from the baseline run; the clusters and the two mutants judged equivalent
// are recorded in notes/mutation-testing.md. The recurring finding: the suite parsed only trees
// with the DEFAULT cell widths (2/2 declared explicitly), so every walker's #address-cells
// handling, inheritance, and parent-vs-own-cells arithmetic was unexercised, and the header's
// boundary comparisons had never been met exactly.
// ================================================================================================

/// A copy of `blob` with one big-endian u32 overwritten at `off`.
fn patched(blob: &[u8], off: usize, val: u32) -> Vec<u8> {
    let mut b = blob.to_vec();
    b[off..off + 4].copy_from_slice(&val.to_be_bytes());
    b
}

/// One big-endian u32 cell, for `#address-cells = 1` layouts.
fn cell32(v: u32) -> Vec<u8> {
    v.to_be_bytes().to_vec()
}

fn minimal_tree() -> Vec<u8> {
    let mut b = Blob::new();
    b.begin_node(b"");
    b.prop(b"#address-cells", &2u32.to_be_bytes());
    b.prop(b"#size-cells", &2u32.to_be_bytes());
    b.end_node();
    b.finish()
}

/// The header comparisons, met exactly. The run showed `bytes.len() < total` could become `<=` or
/// `==` and `last_comp_version > 17` could become `>=` or `==`, because no test had ever handed
/// the parser a buffer of exactly `total` bytes, a buffer with slack, or a blob whose
/// `last_comp_version` was exactly 17; and each offset bound in the `||` chain had never been the
/// one that fired.
#[test]
fn the_header_boundaries_are_exact() {
    let blob = minimal_tree();
    let total = blob.len();

    // A buffer of exactly totalsize parses; slack after it is fine; one byte short is not.
    assert!(DeviceTreeBlob::from_bytes(&blob).is_ok());
    let mut slack = blob.clone();
    slack.extend_from_slice(&[0u8; 8]);
    let dt = DeviceTreeBlob::from_bytes(&slack).unwrap();
    assert_eq!(
        dt.total_size(),
        total,
        "the blob ends where its header says"
    );
    assert_eq!(
        DeviceTreeBlob::from_bytes(&blob[..total - 1]).err(),
        Some(Error::Truncated),
        "one byte short of totalsize"
    );

    // last_comp_version 17 is the newest we accept, and 18 is refused as itself.
    assert!(DeviceTreeBlob::from_bytes(&patched(&blob, 24, 17)).is_ok());
    assert_eq!(
        DeviceTreeBlob::from_bytes(&patched(&blob, 24, 18)).err(),
        Some(Error::UnsupportedVersion(18)),
    );

    // Each block offset alone can be the thing that is out of bounds.
    let t = total as u32;
    assert_eq!(
        DeviceTreeBlob::from_bytes(&patched(&blob, 8, t)).err(),
        Some(Error::Truncated)
    );
    assert_eq!(
        DeviceTreeBlob::from_bytes(&patched(&blob, 12, t)).err(),
        Some(Error::Truncated)
    );
    assert_eq!(
        DeviceTreeBlob::from_bytes(&patched(&blob, 16, t)).err(),
        Some(Error::Truncated)
    );
}

/// The reservation block, with entries in it. The fixtures' is empty, so `reserved_regions` could
/// return `Ok(0)` unconditionally, mis-stride the walk, or treat "starts at zero" as the
/// terminator (the `&&` in the all-zero check becoming `||`), and a reservation AT address zero
/// is exactly the entry firmware writes for its own vector table.
#[test]
fn reservations_are_read_entry_by_entry() {
    let mut b = Blob::new();
    b.begin_node(b"");
    // One prop, so the strings block is non-empty: an empty strings block puts off_strings at
    // exactly totalsize, which from_bytes rightly refuses.
    b.prop(b"#address-cells", &2u32.to_be_bytes());
    b.end_node();
    let blob = b.finish_with_reservations(&[(0, 0x1000), (0x8000_0000, 0x2000)]);
    let dt = DeviceTreeBlob::from_bytes(&blob).unwrap();

    let mut out = [Region { start: 0, size: 0 }; 4];
    assert_eq!(dt.reserved_regions(&mut out), Ok(2));
    assert_eq!((out[0].start, out[0].size), (0, 0x1000));
    assert_eq!((out[1].start, out[1].size), (0x8000_0000, 0x2000));
}

/// `/memory` on a 32-bit-style board: `#address-cells = 1`, two reg entries. Deleting the
/// `#address-cells` match arm leaves the walker decoding with the 2-cell default, which misreads
/// every value; and the second entry is what catches a pair stride that multiplied where it
/// should have added.
#[test]
fn memory_with_one_address_cell() {
    let mut b = Blob::new();
    b.begin_node(b"");
    b.prop(b"#address-cells", &1u32.to_be_bytes());
    b.prop(b"#size-cells", &1u32.to_be_bytes());
    b.begin_node(b"memory@40000000");
    let mut reg = Vec::new();
    reg.extend(cell32(0x4000_0000));
    reg.extend(cell32(0x0100_0000));
    reg.extend(cell32(0x9000_0000));
    reg.extend(cell32(0x0010_0000));
    b.prop(b"device_type", b"memory\0");
    b.prop(b"reg", &reg);
    b.end_node();
    b.end_node();
    let blob = b.finish();
    let dt = DeviceTreeBlob::from_bytes(&blob).unwrap();

    let mut out = [Region { start: 0, size: 0 }; 4];
    assert_eq!(dt.memory_regions(&mut out), Ok(2));
    assert_eq!((out[0].start, out[0].size), (0x4000_0000, 0x0100_0000));
    assert_eq!((out[1].start, out[1].size), (0x9000_0000, 0x0010_0000));
}

/// Cell widths flow DOWN the tree and a node's own declaration applies to its CHILDREN, not to
/// its own `reg`. Three generations pin both rules: the bus inherits the root's 1/1 without
/// declaring anything (kills the inherit index becoming `depth / 1`), and the device declares
/// 2/2 for children it does not have, which must NOT apply to its own reg (kills the decode
/// index becoming `depth` instead of `depth - 1`).
#[test]
fn cell_widths_are_inherited_and_a_reg_uses_its_parents() {
    let mut b = Blob::new();
    b.begin_node(b"");
    b.prop(b"#address-cells", &1u32.to_be_bytes());
    b.prop(b"#size-cells", &1u32.to_be_bytes());
    b.begin_node(b"bus");
    b.begin_node(b"dev@10");
    b.prop(b"#address-cells", &2u32.to_be_bytes());
    b.prop(b"#size-cells", &2u32.to_be_bytes());
    let mut reg = Vec::new();
    reg.extend(cell32(0x1000_0000));
    reg.extend(cell32(0x100));
    reg.extend(cell32(0x2000_0000));
    reg.extend(cell32(0x200));
    b.prop(b"reg", &reg);
    b.end_node();
    b.end_node();
    b.end_node();
    let blob = b.finish();
    let dt = DeviceTreeBlob::from_bytes(&blob).unwrap();

    let mut out = [Region { start: 0, size: 0 }; 4];
    assert_eq!(dt.node_reg(b"dev@", &mut out), Ok(2));
    assert_eq!((out[0].start, out[0].size), (0x1000_0000, 0x100));
    assert_eq!((out[1].start, out[1].size), (0x2000_0000, 0x200));
}

/// Only a name match may set the target: with `||` in the match condition, the first depth-2 node
/// of any name is taken, and the spi node's reg comes back for a uart query.
#[test]
fn a_prefix_finds_its_node_not_the_first_node() {
    let mut b = Blob::new();
    b.begin_node(b"");
    b.prop(b"#address-cells", &2u32.to_be_bytes());
    b.prop(b"#size-cells", &2u32.to_be_bytes());
    b.begin_node(b"spi@0");
    b.prop(b"reg", &reg64(0x111, 0x10));
    b.end_node();
    b.begin_node(b"uart@9000000");
    b.prop(b"reg", &reg64(0x900_0000, 0x1000));
    b.end_node();
    b.end_node();
    let blob = b.finish();
    let dt = DeviceTreeBlob::from_bytes(&blob).unwrap();

    let mut out = [Region { start: 0, size: 0 }; 2];
    assert_eq!(dt.node_reg(b"uart@", &mut out), Ok(1));
    assert_eq!((out[0].start, out[0].size), (0x900_0000, 0x1000));
}

/// A matched node stays matched across its children: the `END_NODE` bookkeeping compares depths
/// with `==`, and `!=` clears the target at the first `CHILD`'s close. The spec puts props before
/// children, but this parser accepts either order, and a reg after a child is the blob that
/// tells the two apart. That is this file's charter: blobs dtc would refuse.
#[test]
fn a_matched_node_survives_its_children_closing() {
    let mut b = Blob::new();
    b.begin_node(b"");
    b.prop(b"#address-cells", &2u32.to_be_bytes());
    b.prop(b"#size-cells", &2u32.to_be_bytes());
    b.begin_node(b"m@1");
    b.begin_node(b"child");
    b.end_node();
    b.prop(b"reg", &reg64(0xAB00, 0x40));
    b.end_node();
    b.end_node();
    let blob = b.finish();
    let dt = DeviceTreeBlob::from_bytes(&blob).unwrap();

    let mut out = [Region { start: 0, size: 0 }; 2];
    assert_eq!(dt.node_reg(b"m@", &mut out), Ok(1));
    assert_eq!((out[0].start, out[0].size), (0xAB00, 0x40));
}

/// The cell stack is 16 deep and the guard is `depth < 16`: at depth exactly 16 a declared
/// `#address-cells` must be ignored, not recorded, because recording it indexes one past the
/// stack. `<=` here is an out-of-bounds panic in the parser the kernel runs on firmware bytes.
#[test]
fn a_declaration_at_the_stacks_edge_is_ignored_not_indexed() {
    let mut b = Blob::new();
    b.begin_node(b"");
    for _ in 0..15 {
        b.begin_node(b"bus");
    }
    b.prop(b"#address-cells", &1u32.to_be_bytes());
    for _ in 0..16 {
        b.end_node();
    }
    let blob = b.finish();
    let dt = DeviceTreeBlob::from_bytes(&blob).unwrap();

    let mut out = [Region { start: 0, size: 0 }; 1];
    assert_eq!(dt.node_reg(b"absent@", &mut out), Ok(0));
}

/// The compatible walker's own copies of the same rules: the root cannot be a device (its match
/// guard requires depth >= 2, and `true` there hands back the root's reg), the cell widths
/// inherit, and a matching child's reg decodes with its parent's widths.
#[test]
fn compatible_respects_the_root_and_the_cell_widths() {
    let mut b = Blob::new();
    b.begin_node(b"");
    b.prop(b"#address-cells", &1u32.to_be_bytes());
    b.prop(b"#size-cells", &1u32.to_be_bytes());
    b.prop(b"compatible", b"root,thing\0");
    b.prop(b"reg", &cell32(0xDEAD));
    b.begin_node(b"rtc@101000");
    b.prop(b"#address-cells", &2u32.to_be_bytes());
    b.prop(b"#size-cells", &2u32.to_be_bytes());
    let mut reg = Vec::new();
    reg.extend(cell32(0x0010_1000));
    reg.extend(cell32(0x1000));
    b.prop(b"reg", &reg);
    b.prop(b"compatible", b"google,goldfish-rtc\0");
    b.end_node();
    b.end_node();
    let blob = b.finish();
    let dt = DeviceTreeBlob::from_bytes(&blob).unwrap();

    let mut out = [Region { start: 0, size: 0 }; 2];
    assert_eq!(
        dt.node_reg_compatible(b"root,thing", &mut out),
        Ok(0),
        "the root is not a device"
    );
    assert_eq!(
        dt.node_reg_compatible(b"google,goldfish-rtc", &mut out),
        Ok(1)
    );
    assert_eq!((out[0].start, out[0].size), (0x0010_1000, 0x1000));
}

/// Property lookup is by name, not position, and the walk has to stride over values whose
/// lengths are not multiples of four. Three props of awkward lengths, queried out of order, with
/// exact bytes; a name the node does not have is None, and a node that does not exist is None.
#[test]
fn props_are_found_by_name_not_position() {
    let mut b = Blob::new();
    b.begin_node(b"");
    b.begin_node(b"chosen");
    b.prop(b"alpha", b"AAAAA");
    b.prop(b"bootargs", b"console=ttyAMA0\0");
    b.prop(b"beta", &0xDDCC_BBAA_9988_7766u64.to_be_bytes());
    b.end_node();
    b.end_node();
    let blob = b.finish();
    let dt = DeviceTreeBlob::from_bytes(&blob).unwrap();

    assert_eq!(
        dt.node_prop(b"chosen", b"bootargs"),
        Ok(Some(&b"console=ttyAMA0\0"[..]))
    );
    assert_eq!(dt.node_prop(b"chosen", b"alpha"), Ok(Some(&b"AAAAA"[..])));
    assert_eq!(
        dt.node_prop(b"chosen", b"beta"),
        Ok(Some(&0xDDCC_BBAA_9988_7766u64.to_be_bytes()[..]))
    );
    assert_eq!(dt.node_prop(b"chosen", b"gamma"), Ok(None));
    assert_eq!(dt.node_prop(b"absent", b"alpha"), Ok(None));
}

/// `node_props` answers for every matching node, and "has no such property" is a different
/// answer from "is not there": two cpu@ nodes, one of which does not describe itself.
#[test]
fn node_props_tells_missing_prop_from_missing_node() {
    let mut b = Blob::new();
    b.begin_node(b"");
    b.begin_node(b"cpu@0");
    b.prop(b"riscv,isa", b"rv64gc\0");
    b.end_node();
    b.begin_node(b"cpu@1");
    b.end_node();
    b.end_node();
    let blob = b.finish();
    let dt = DeviceTreeBlob::from_bytes(&blob).unwrap();

    let mut out = [None; 4];
    assert_eq!(dt.node_props(b"cpu@", b"riscv,isa", &mut out), Ok(2));
    assert_eq!(out[0], Some(&b"rv64gc\0"[..]));
    assert_eq!(out[1], None);
}

/// The initrd contract, boundary by boundary: 4-byte ints (the 32-bit platform shape, and the
/// deleted-match-arm survivor), an exclusive end so start == end is "no initrd", and the chosen
/// node found by NAME at depth 2, so a depth-2 node of another name carrying the same props is
/// not an initrd.
#[test]
fn initrd_reads_widths_and_refuses_the_empty_and_the_misnamed() {
    let build = |name: &[u8], start: u32, end: u32| {
        let mut b = Blob::new();
        b.begin_node(b"");
        b.begin_node(name);
        b.prop(b"linux,initrd-start", &start.to_be_bytes());
        b.prop(b"linux,initrd-end", &end.to_be_bytes());
        b.end_node();
        b.end_node();
        b.finish()
    };

    let blob = build(b"chosen", 0x4800_0000, 0x4800_8000);
    let dt = DeviceTreeBlob::from_bytes(&blob).unwrap();
    let r = dt.initrd().unwrap().expect("a real initrd range");
    assert_eq!((r.start, r.size), (0x4800_0000, 0x8000));

    let blob = build(b"chosen", 0x4800_0000, 0x4800_0000);
    let dt = DeviceTreeBlob::from_bytes(&blob).unwrap();
    assert_eq!(dt.initrd(), Ok(None), "start == end is an empty initrd");

    let blob = build(b"notchosen", 0x4800_0000, 0x4800_8000);
    let dt = DeviceTreeBlob::from_bytes(&blob).unwrap();
    assert_eq!(
        dt.initrd(),
        Ok(None),
        "the props only mean initrd inside /chosen"
    );
}

// The tests above came from the baseline run's survivor list; the ones below close the gaps that
// list still had after them. Several survivors dodge the earlier tests by coincidence of shape
// (a device that is a direct child of the root never reads the inherited cell slots; a matched
// node that is the first child never meets a foreign END_NODE), so each test here names the shape
// that was still missing.

/// `totalsize` against the header's own length, met exactly. A claim smaller than the header
/// cannot hold the header that makes it, and is refused even with a big buffer and in-range
/// offsets, so nothing else can be the reason. A claim of exactly `HEADER_LEN` is the smallest
/// self-consistent one: the header checks pass and the walkers report their own truncation.
#[test]
fn totalsize_meets_the_header_length_exactly() {
    let blob = minimal_tree();

    let mut short = patched(&blob, 4, 39);
    for off in [8, 12, 16] {
        short = patched(&short, off, 0);
    }
    assert_eq!(
        DeviceTreeBlob::from_bytes(&short).err(),
        Some(Error::Truncated)
    );

    let mut bare = patched(&blob, 4, 40);
    for off in [8, 12, 16] {
        bare = patched(&bare, off, 8);
    }
    assert!(DeviceTreeBlob::from_bytes(&bare).is_ok());
}

/// The root cannot be a device for the name walker either (`compatible_respects_the_root...`
/// pins the other walker): a `reg` on the root must not come back for a name the tree does not
/// contain. The last `&&` of the match condition becoming `||` targets the root, whose empty
/// name matches nothing, the moment the walk begins.
#[test]
fn a_roots_reg_is_never_a_named_devices() {
    let mut b = Blob::new();
    b.begin_node(b"");
    b.prop(b"#address-cells", &2u32.to_be_bytes());
    b.prop(b"#size-cells", &2u32.to_be_bytes());
    let mut reg = Vec::new();
    reg.extend(cell32(0));
    reg.extend(cell32(0xBEEF));
    reg.extend(cell32(0x10));
    b.prop(b"reg", &reg);
    b.end_node();
    let blob = b.finish();
    let dt = DeviceTreeBlob::from_bytes(&blob).unwrap();

    let mut out = [Region { start: 0, size: 0 }; 2];
    assert_eq!(dt.node_reg(b"absent@", &mut out), Ok(0));
}

/// The compatible walker inherits cell widths through a silent intermediary, the same
/// three-generation rule `cell_widths_are_inherited...` pins for the name walker; the earlier
/// compatible test's device sits directly under the root, so the inherited slots were never the
/// ones read. The size's high cell is nonzero, so a decode with anything but the inherited 1/2
/// finds no pair at all or reports a size of 1.
#[test]
fn compatible_inherits_cell_widths_through_a_silent_bus() {
    let mut b = Blob::new();
    b.begin_node(b"");
    b.prop(b"#address-cells", &1u32.to_be_bytes());
    b.prop(b"#size-cells", &2u32.to_be_bytes());
    b.begin_node(b"bus");
    b.begin_node(b"dev@2000");
    let mut reg = Vec::new();
    reg.extend(cell32(0x2000));
    reg.extend(cell32(0x1));
    reg.extend(cell32(0x2000));
    b.prop(b"reg", &reg);
    b.prop(b"compatible", b"nife,testdev\0");
    b.end_node();
    b.end_node();
    b.end_node();
    let blob = b.finish();
    let dt = DeviceTreeBlob::from_bytes(&blob).unwrap();

    let mut out = [Region { start: 0, size: 0 }; 2];
    assert_eq!(dt.node_reg_compatible(b"nife,testdev", &mut out), Ok(1));
    assert_eq!((out[0].start, out[0].size), (0x2000, 0x1_0000_2000));
}

/// A `reg` before any node has no parent to decode against, and the `depth >= 2` guard on the
/// compatible walker's `reg` arm is what separates "walk past it" from indexing the cell stack
/// at depth minus one, which underflows at zero. Nothing writes such a blob; this parser reads
/// blobs nothing should have written.
#[test]
fn a_reg_before_the_root_is_walked_past() {
    let mut b = Blob::new();
    b.prop(b"reg", &reg64(0x1000, 0x100));
    b.begin_node(b"");
    b.end_node();
    let blob = b.finish();
    let dt = DeviceTreeBlob::from_bytes(&blob).unwrap();

    let mut out = [Region { start: 0, size: 0 }; 2];
    assert_eq!(dt.node_reg_compatible(b"absent", &mut out), Ok(0));
}

/// The prop walker's target may only be a matched node: not the root, which is what `||` in the
/// match condition produces (the root's target check is the first that can pass), and not
/// nothing, which is what an inverted `END_NODE` comparison produces (the first sibling to close
/// would end the search). The root and a decoy sibling carry the same property name with
/// different values so either wrong answer is visible, not just a wrong count.
#[test]
fn node_prop_ignores_the_root_and_survives_a_closing_sibling() {
    let mut b = Blob::new();
    b.begin_node(b"");
    b.prop(b"status", b"root\0");
    b.begin_node(b"decoy");
    b.prop(b"status", b"decoy\0");
    b.end_node();
    b.begin_node(b"uart@100");
    b.prop(b"status", b"okay\0");
    b.end_node();
    b.end_node();
    let blob = b.finish();
    let dt = DeviceTreeBlob::from_bytes(&blob).unwrap();

    assert_eq!(dt.node_prop(b"uart@", b"status"), Ok(Some(&b"okay\0"[..])));
}

/// `/reserved-memory` children default to the ROOT's cell widths, read at depth 1 and nowhere
/// else. The riscv fixture's root declares 2/2, which the defaults already are, so the depth-1
/// gate and both of its match arms were deletable invisibly; a 1/1 root is the tree that
/// notices.
#[test]
fn reserved_memory_defaults_to_the_roots_cell_widths() {
    let mut b = Blob::new();
    b.begin_node(b"");
    b.prop(b"#address-cells", &1u32.to_be_bytes());
    b.prop(b"#size-cells", &1u32.to_be_bytes());
    b.begin_node(b"reserved-memory");
    b.begin_node(b"fw@80000000");
    let mut reg = Vec::new();
    reg.extend(cell32(0x8000_0000));
    reg.extend(cell32(0x4_0000));
    b.prop(b"reg", &reg);
    b.end_node();
    b.end_node();
    b.end_node();
    let blob = b.finish();
    let dt = DeviceTreeBlob::from_bytes(&blob).unwrap();

    let mut out = [Region { start: 0, size: 0 }; 4];
    assert_eq!(dt.reserved_memory_regions(&mut out), Ok(1));
    assert_eq!((out[0].start, out[0].size), (0x8000_0000, 0x4_0000));
}

/// And `/reserved-memory` may override those widths for its own children, which the fixture
/// never does. The child's `compatible` sits before its `reg` because the decode condition
/// requires child depth AND the name `reg`: with `||` the compatible string's sixteen bytes
/// decode as two plausible extra regions, and the count says so.
#[test]
fn reserved_memory_honours_its_own_declared_widths() {
    let mut b = Blob::new();
    b.begin_node(b"");
    b.begin_node(b"reserved-memory");
    b.prop(b"#address-cells", &1u32.to_be_bytes());
    b.prop(b"#size-cells", &1u32.to_be_bytes());
    b.begin_node(b"pool@1000");
    b.prop(b"compatible", b"shared-dma-pool\0");
    let mut reg = Vec::new();
    reg.extend(cell32(0x1000));
    reg.extend(cell32(0x2000));
    b.prop(b"reg", &reg);
    b.end_node();
    b.end_node();
    b.end_node();
    let blob = b.finish();
    let dt = DeviceTreeBlob::from_bytes(&blob).unwrap();

    let mut out = [Region { start: 0, size: 0 }; 4];
    assert_eq!(dt.reserved_memory_regions(&mut out), Ok(1));
    assert_eq!((out[0].start, out[0].size), (0x1000, 0x2000));
}

/// `/chosen` stops meaning chosen when it closes: with the `END_NODE` comparison inverted the
/// walker keeps attributing properties to it, and a later sibling's `linux,initrd-end`
/// overwrites the real one, returning an initrd of the wrong size.
#[test]
fn initrd_properties_after_chosen_closes_do_not_count() {
    let mut b = Blob::new();
    b.begin_node(b"");
    b.begin_node(b"chosen");
    b.prop(b"linux,initrd-start", &0x4800_0000u64.to_be_bytes());
    b.prop(b"linux,initrd-end", &0x4802_0000u64.to_be_bytes());
    b.end_node();
    b.begin_node(b"leftover");
    b.prop(b"linux,initrd-end", &0x4BAD_0000u64.to_be_bytes());
    b.end_node();
    b.end_node();
    let blob = b.finish();
    let dt = DeviceTreeBlob::from_bytes(&blob).unwrap();

    let r = dt.initrd().unwrap().expect("the real range from /chosen");
    assert_eq!((r.start, r.size), (0x4800_0000, 0x2_0000));
}
