//! The search index: one byte layout, agreed between the builder that runs on the host and the
//! reader that runs confined.
//!
//! # Why an index at all, and why it is built on the host
//!
//! There is no directory iteration in this system. `readdir` refuses in the std PAL and the §27
//! file contract has no such verb, and the capability model argues against adding one: **enumeration
//! is authority**, and a viewer that can list a directory can discover what it was not given. So
//! "what pages exist" is not something the guest can find out by looking. It is something a builder
//! computes where there are no constraints and ships as a file, which is the same answer Unix's
//! `mandb` reached for a different reason (scanning was slow).
//!
//! # The one property the layout is designed for
//!
//! **A reader holds one 4 KiB page and never more.** That is not a budget chosen for tidiness: a
//! client of the file contract shares exactly one frame with the FS server, and a shell that had to
//! buffer a whole index would need a memory grant to search. So every section starts on a page
//! boundary and every record divides 4096 evenly, which together mean **a reader with one page in
//! hand never sees half a record**, and a lookup is a binary search over pages rather than a scan
//! over bytes.
//!
//! A lookup costs `ceil(log2(term pages)) + 1` page reads: the search narrows to a page by comparing
//! each candidate page's first term, then finishes inside that page with no further IO. For this
//! repository's corpus (see the numbers `cargo xtask manual` prints) that is single digits.
//!
//! # Layout
//!
//! ```text
//!   page 0            header (below), rest zero
//!   page_off          page records, 128 bytes each, 32 per page
//!   term_off          term records, 32 bytes each, 128 per page, sorted by term bytes
//!   post_off          postings, 4 bytes each, 1024 per page, grouped by term
//! ```
//!
//! # EXAMPLES
//!
//! The worked example lives on the `build` function, because it needs the `builder` feature to run
//! and rustdoc will only compile it when that feature is on. [`normalize`] and [`tokens`] are the
//! two functions a caller on either side reaches for, and both are exercised by the tests at the
//! foot of this file.
//!
//! # BUGS
//!
//! - **A term is truncated to [`TERM_MAX`] bytes**, so two identifiers that agree in their first 24
//!   characters share a posting list and a query for either finds both. Nothing in this corpus
//!   collides; a longer identifier set would.
//! - **Terms are ASCII-folded and split on anything that is not a letter or a digit**, so
//!   `filesystem_proto` indexes as `fs` and `proto` and a search for `filesystem_proto` finds pages that mention
//!   either. That is the same behaviour as `apropos` and it is wrong in the same way.
//! - **There is no phrase search**, because it wants a position list and this index deliberately
//!   stores none. Ranking (below) only ever needed a page's *length*, which is a single `u32` per
//!   page record rather than a position per posting.
//! - **The index does not record which line a term appeared on**, so a result names a page and not
//!   a place in it. Storing positions would multiply the postings section by the average term
//!   frequency, and the reader has no memory to spend on it.
//! - **A version mismatch is refused, not migrated.** [`Header::parse`] rejects any shard whose
//!   [`VERSION`] is not this reader's, so an old guest meeting a new store answers "that is not an
//!   index this reader knows" rather than misreading a record layout. There is no migration path
//!   and there does not need to be one yet: every shard in the tree is a build artifact,
//!   regenerated by `cargo xtask manual`, so the format and its reader ship together. The day a
//!   shard arrives from somewhere the build did not produce, this is the decision to revisit.
//! - **A search keeps [`RESULTS_MAX`] results and counts the rest.** [`Ranked::offered`] reports
//!   the total, so a caller can say "16 of 43", and a caller that prints the results without it is
//!   implying an answer it did not get.
//! - ~~**Ranking is occurrence count and nothing else.**~~ **It divides by document length now**
//!   (`score`, 2026-08-22): a page's stored [`Page::tokens`] is the denominator, so a short page
//!   where a term is dense outranks a long page where it mentions the term only in passing, even
//!   with a smaller raw count. [`Found::count`] still reports the raw occurrence count; only the
//!   order changed. Ranking still has no notion of a phrase or a position, and still cannot tell
//!   a heading mention from a passing one, because the index stores neither.
//! - **A search answer names pages, never grants them.** That is the point rather than a
//!   limitation: what a result carries is a *name* ([`Found::location`]), and reading the page is a
//!   separate act in which the reader designates that name and whoever holds the store backs it.
//!   Search cannot widen what its caller could already reach.

/// The page size the whole layout is built around: the frame a client shares with the FS server.
pub const PAGE: usize = 4096;

/// The magic that starts a well-formed index.
pub const MAGIC: [u8; 8] = *b"CRKRMAN1";

/// **The layout version, in bytes 8..12 of the header.**
///
/// The builder has written this since phase 1 and nothing read it until phase 2, which is the
/// shape AGENTS.md calls a foot gun: a version field nobody checks is a field that cannot do the
/// one thing it exists for. A shard whose version is not this one is [`Error::BadVersion`], and
/// the reader stops rather than reading a record layout it does not know. See `BUGS` for what
/// that costs.
///
/// **2 (2026-08-22): a page record grew a `tokens` field**, the page's total token count, spent
/// out of the six bytes [`PAGE_REC`] already held spare (`notes/manual.md`'s "where this goes
/// next" priced this at exactly one division and no format growth; it is four of the six). It is
/// what lets ranking divide by document length instead of counting raw occurrences. A version-1
/// shard has no such field, so the bump is real rather than ceremonial: every shard in the tree
/// is a build artifact regenerated by `cargo xtask manual`, so there is nothing to migrate, only
/// a reader that must not guess.
pub const VERSION: u32 = 2;

/// **The directory the store is installed in**, relative to the root of whatever directory
/// capability the searcher holds. `doc/bundles` lists the bundles; `doc/<bundle>/index` is one
/// bundle's shard, and `doc/<bundle>/<page>.md` are its pages.
///
/// Here rather than in the builder or in the shell because it is the definition of the store, and
/// **a store layout is a thing two programs agree on** (AGENTS.md rule 7): the host writes these
/// names and the guest opens them. Spelling them twice is the drift `c_seam` is the scar for.
pub const STORE_DIR: &str = "doc";

/// The manifest naming the installed bundles, one per line, inside [`STORE_DIR`].
///
/// **A file rather than a directory listing**, which is the whole milestone in one constant: there
/// is no directory iteration in this system, and adding one would be adding authority.
pub const MANIFEST: &str = "bundles";

/// One bundle's index shard, inside `<STORE_DIR>/<bundle>/`.
pub const SHARD: &str = "index";

/// Bytes in a page record.
pub const PAGE_REC: usize = 128;
/// Bytes in a term record.
pub const TERM_REC: usize = 32;
/// Bytes in a posting.
pub const POST_REC: usize = 4;

/// The longest page path an index can name.
pub const PATH_MAX: usize = 72;
/// The longest page title an index can carry.
pub const TITLE_MAX: usize = 48;
/// The longest term an index stores; longer ones are truncated to it.
pub const TERM_MAX: usize = 24;

/// What went wrong reading an index.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Error {
    /// The first eight bytes are not [`MAGIC`].
    BadMagic,
    /// The header is shorter than a header.
    Truncated,
    /// The magic is right and the layout version is not [`VERSION`]. A separate variant from
    /// [`BadMagic`](Error::BadMagic) because the two are different facts about the world: one file
    /// is not an index at all, and the other is an index this reader is too old or too new for.
    BadVersion {
        /// What the file claims to be.
        found: u32,
    },
}

/// The header, parsed. Every offset is a byte offset from the start of the file and is a multiple
/// of [`PAGE`].
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub struct Header {
    /// The layout version, which [`Header::parse`] has already checked is [`VERSION`]. Carried
    /// rather than dropped so a caller printing what it opened can say which one it read.
    pub version: u32,
    /// How many pages the index describes.
    pub pages: u32,
    /// How many distinct terms it holds.
    pub terms: u32,
    /// How many postings, across all terms.
    pub postings: u32,
    /// Byte offset of the page records.
    pub page_off: u64,
    /// Byte offset of the term records.
    pub term_off: u64,
    /// Byte offset of the postings.
    pub post_off: u64,
    /// The index's total size in bytes, which is what a caller checks a file against.
    pub total: u64,
}

impl Header {
    /// Read a header out of the index's first page.
    pub fn parse(first: &[u8]) -> Result<Header, Error> {
        if first.len() < 64 {
            return Err(Error::Truncated);
        }
        if first[..8] != MAGIC {
            return Err(Error::BadMagic);
        }
        let version = u32(first, 8);
        if version != VERSION {
            return Err(Error::BadVersion { found: version });
        }
        Ok(Header {
            version,
            pages: u32(first, 12),
            terms: u32(first, 16),
            postings: u32(first, 20),
            page_off: u64v(first, 24),
            term_off: u64v(first, 32),
            post_off: u64v(first, 40),
            total: u64v(first, 48),
        })
    }
}

/// A source of index pages.
///
/// The reader asks for a page by number and gets it or does not; it never seeks, never reads a byte
/// range, and never holds two pages at once. That is the whole interface, and it is this small so
/// that the guest implementation is a single `filesystem_proto` `READ` and the host implementation is a
/// slice.
pub trait Pages {
    /// Fill `out` with page `index` of the file. `false` means the read failed or ran off the end.
    fn page(&mut self, index: u64, out: &mut [u8; PAGE]) -> bool;
}

/// A [`Pages`] over bytes already in memory, which is what the host and the tests use.
pub struct Slice<'a>(pub &'a [u8]);

impl Pages for Slice<'_> {
    fn page(&mut self, index: u64, out: &mut [u8; PAGE]) -> bool {
        let start = index as usize * PAGE;
        if start >= self.0.len() {
            return false;
        }
        let end = (start + PAGE).min(self.0.len());
        out[..end - start].copy_from_slice(&self.0[start..end]);
        out[end - start..].fill(0);
        true
    }
}

/// A term that was found: where its postings are and how many there are.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub struct Hit {
    /// Index of this term's first posting.
    pub first: u32,
    /// How many pages mention the term.
    pub count: u16,
}

/// One page's mention of a term.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub struct Posting {
    /// Which page record, by index.
    pub page: u16,
    /// How many times the term occurs on it.
    pub count: u16,
}

/// A page the index names.
#[derive(Clone, Copy)]
pub struct Page {
    path: [u8; PATH_MAX],
    path_len: u8,
    title: [u8; TITLE_MAX],
    title_len: u8,
    tokens: u32,
}

impl Page {
    /// The page's path, as the store names it.
    pub fn path(&self) -> &[u8] {
        &self.path[..self.path_len as usize]
    }
    /// The page's title: its first level-one heading, or its path if it has none.
    pub fn title(&self) -> &[u8] {
        &self.title[..self.title_len as usize]
    }
    /// **How many tokens [`tokens`] emitted over this page's text**, the denominator ranking
    /// divides by. Not a byte count and not a word count in the ordinary sense: it is the same
    /// count the builder used to fill the postings, so a page's density for a term is exactly
    /// `count / this`.
    pub fn tokens(&self) -> u32 {
        self.tokens
    }
}

/// Fold a query word the way the builder folded the text, so the two can be compared.
///
/// Returns the length written into `out`. A word that folds to nothing (punctuation alone) returns
/// zero and is not a term.
pub fn normalize(word: &[u8], out: &mut [u8; TERM_MAX]) -> usize {
    let mut n = 0;
    for &b in word {
        if n == TERM_MAX {
            break;
        }
        if b.is_ascii_alphanumeric() {
            out[n] = b.to_ascii_lowercase();
            n += 1;
        }
    }
    n
}

/// Split text into terms the way the builder does: runs of ASCII letters and digits, folded to
/// lower case, truncated to [`TERM_MAX`], and dropped if shorter than two characters.
///
/// A one-character term is dropped because it costs a posting list per letter of the alphabet and
/// answers no question anybody asks a manual.
///
/// # An underscore-joined name is also one term, and it has to be
///
/// `line_editor` yields `line`, `editor` **and** `lineeditor`, and the third one is not a nicety.
/// [`normalize`] drops every non-alphanumeric byte, so a reader who types `line_editor` looks up
/// `lineeditor`; a tokeniser that only split on the underscore would never have written that term,
/// and the lookup could not match however many pages said it. The two halves of this module
/// disagreed about exactly that until 2026-08-18, and `a_query_folds_the_way_the_text_did` asserted
/// they agreed while testing only a word with no underscore in it.
///
/// **Only the underscore joins.** This repository writes `snake_case` identifiers in running prose
/// constantly (`filesystem_proto`, `grant_plan`, `terminal_sink_caretaker`), so they are the names a reader
/// most wants to search for, and the underscore is unambiguous here in a way the hyphen is not:
/// joining across `-` would manufacture a term out of every hyphenated phrase in the corpus. The
/// renderer narrowed emphasis for the same reason and records it in its own `BUGS`.
pub fn tokens(text: &[u8], mut f: impl FnMut(&[u8])) {
    let mut buf = [0u8; TERM_MAX];
    let mut n = 0;
    // The compound: this run and every run underscore-joined ahead of it, with the underscores
    // taken out, which is exactly what `normalize` will do to the query.
    let mut joined = [0u8; TERM_MAX];
    let mut jn = 0;
    let mut parts = 0usize;
    for &b in text {
        if b.is_ascii_alphanumeric() {
            if n < TERM_MAX {
                buf[n] = b.to_ascii_lowercase();
                n += 1;
            }
            if jn < TERM_MAX {
                joined[jn] = b.to_ascii_lowercase();
                jn += 1;
            }
            continue;
        }
        if n >= 2 {
            f(&buf[..n]);
        }
        if n > 0 {
            parts += 1;
        }
        n = 0;
        if b != b'_' {
            // Emitted only when there was something to join, so an ordinary word is not offered
            // twice and the term table does not double for prose.
            if parts > 1 && jn >= 2 {
                f(&joined[..jn]);
            }
            jn = 0;
            parts = 0;
        }
    }
    if n >= 2 {
        f(&buf[..n]);
    }
    if n > 0 {
        parts += 1;
    }
    if parts > 1 && jn >= 2 {
        f(&joined[..jn]);
    }
}

/// **Read the bundle manifest**, calling `f` once per installed bundle name.
///
/// The format is one name per line, which is the whole of it: the manifest exists because nothing
/// can list a directory, so it is the smallest thing that can answer "what is installed" and it
/// should stay readable by a person holding `cat`. Blank lines are skipped and `\r` is trimmed, so
/// a manifest that has been through a text editor still reads.
pub fn bundles(text: &[u8], mut f: impl FnMut(&[u8])) {
    for line in text.split(|&b| b == b'\n') {
        let line = match line.split_last() {
            Some((b'\r', head)) => head,
            _ => line,
        };
        if !line.is_empty() {
            f(line);
        }
    }
}

/// Look a term up, reading at most `ceil(log2(term pages)) + 1` pages.
///
/// The search is over *pages*, not over records: each probe reads one page and compares the term it
/// starts with, which narrows the range by half for one read. The final page is searched in memory,
/// where it costs nothing.
pub fn lookup(h: &Header, term: &[u8], src: &mut impl Pages) -> Option<Hit> {
    let mut key = [0u8; TERM_MAX];
    let n = normalize(term, &mut key);
    if n == 0 || h.terms == 0 {
        return None;
    }
    let key = &key[..n];

    let per = PAGE / TERM_REC;
    let first = h.term_off / PAGE as u64;
    let last = (h.terms as u64 - 1) / per as u64;

    let mut buf = [0u8; PAGE];
    let mut lo = 0u64;
    let mut hi = last;
    while lo < hi {
        let mid = lo + (hi - lo).div_ceil(2);
        if !src.page(first + mid, &mut buf) {
            return None;
        }
        if cmp(&buf[..TERM_REC], key) == core::cmp::Ordering::Greater {
            hi = mid - 1;
        } else {
            lo = mid;
        }
    }
    if !src.page(first + lo, &mut buf) {
        return None;
    }
    let here = (h.terms as u64 - lo * per as u64).min(per as u64) as usize;
    for i in 0..here {
        let rec = &buf[i * TERM_REC..(i + 1) * TERM_REC];
        if cmp(rec, key) == core::cmp::Ordering::Equal {
            return Some(Hit {
                first: u32(rec, TERM_MAX),
                count: u16v(rec, TERM_MAX + 4),
            });
        }
    }
    None
}

/// Read up to `out.len()` of a hit's postings, returning how many were read.
pub fn postings(h: &Header, hit: &Hit, src: &mut impl Pages, out: &mut [Posting]) -> usize {
    let mut buf = [0u8; PAGE];
    let per = PAGE / POST_REC;
    let want = (hit.count as usize).min(out.len());
    let mut done = 0;
    let mut loaded = u64::MAX;
    while done < want {
        let at = hit.first as usize + done;
        let page = h.post_off / PAGE as u64 + (at / per) as u64;
        if page != loaded {
            if !src.page(page, &mut buf) {
                return done;
            }
            loaded = page;
        }
        let off = (at % per) * POST_REC;
        out[done] = Posting {
            page: u16v(&buf, off),
            count: u16v(&buf, off + 2),
        };
        done += 1;
    }
    done
}

/// Read one page record.
pub fn page_record(h: &Header, i: u16, src: &mut impl Pages) -> Option<Page> {
    if i as u32 >= h.pages {
        return None;
    }
    let per = PAGE / PAGE_REC;
    let mut buf = [0u8; PAGE];
    if !src.page(
        h.page_off / PAGE as u64 + (i as usize / per) as u64,
        &mut buf,
    ) {
        return None;
    }
    let rec = &buf[(i as usize % per) * PAGE_REC..][..PAGE_REC];
    let mut p = Page {
        path: [0; PATH_MAX],
        path_len: rec[PATH_MAX + TITLE_MAX].min(PATH_MAX as u8),
        title: [0; TITLE_MAX],
        title_len: rec[PATH_MAX + TITLE_MAX + 1].min(TITLE_MAX as u8),
        tokens: u32(rec, PATH_MAX + TITLE_MAX + 2),
    };
    p.path.copy_from_slice(&rec[..PATH_MAX]);
    p.title
        .copy_from_slice(&rec[PATH_MAX..PATH_MAX + TITLE_MAX]);
    Some(p)
}

// ---- the answer: searching a store of shards, with no allocator ------------------------------

/// The longest store location a result can name: `<STORE_DIR>/<bundle>/<page>`.
///
/// Ninety-six rather than [`PATH_MAX`] plus slack, because a location is not a path in the index:
/// it is three short components, and the widest real one today (`doc/swish/line-discipline.md`) is
/// twenty-eight bytes. A location longer than this is truncated and [`Found::truncated`] says so,
/// for the reason the renderer gives about losing text silently.
pub const LOCATION_MAX: usize = 96;

/// **How many results one search keeps.**
///
/// Sixteen, and the number is the reader's rather than the index's: a search answer is something a
/// person reads at a prompt before deciding what to open, and a screen of a terminal this system
/// has is 16 rows (`video_terminal`) or a serial window. Every result past the sixteenth is counted
/// and not kept, and [`Ranked::offered`] is what lets the caller say so instead of implying the
/// answer was complete.
pub const RESULTS_MAX: usize = 16;

/// **The fixed-point scale `score` multiplies by**, so `count / tokens` survives as an integer
/// worth comparing rather than rounding to zero every time a term is not the whole page.
///
/// A million rather than something smaller because the numerator, `count as u64 * SCORE_SCALE`,
/// has to fit `u64` for the largest `count` this layout can carry (`u16::MAX`) and the smallest
/// meaningful `tokens` (one): `65535 * 1_000_000` is about 6.55e10, nowhere near `u64::MAX`. The
/// result then fits `u32` because a term cannot occur more times than the page holds tokens, so
/// `count <= tokens` in the honest case and the ratio never exceeds [`SCORE_SCALE`] itself.
const SCORE_SCALE: u64 = 1_000_000;

/// **Term frequency over document length, the one division `notes/manual.md` priced this at.**
///
/// `page_tokens` is clamped to at least one so a term cannot score as infinitely dense on a page
/// the builder recorded as empty (which should not happen, since a page contributing zero tokens
/// contributes no postings either, but the clamp costs nothing and a divide by zero is not a
/// trap worth leaving in a `no_std` reader).
fn score(count: u16, page_tokens: u32) -> u32 {
    let denom = (page_tokens as u64).max(1);
    ((count as u64 * SCORE_SCALE) / denom).min(u32::MAX as u64) as u32
}

/// One line of a search answer: a page, where a reader can find it, and how strongly it matched.
///
/// It holds **copies** rather than borrows, and that is what makes a merge across shards possible
/// at all: each shard is opened, searched and closed in turn, and a result borrowed from the page
/// buffer would name bytes that the next shard's first read overwrites.
#[derive(Clone, Copy)]
pub struct Found {
    location: [u8; LOCATION_MAX],
    location_len: u8,
    truncated: bool,
    title: [u8; TITLE_MAX],
    title_len: u8,
    /// The page's path as the index records it, which is where the page came from in the source
    /// tree rather than where it is installed. See [`Found::location`] for the difference.
    origin: [u8; PATH_MAX],
    origin_len: u8,
    /// How many times the term occurs on this page. Printed as-is: what a reader sees is the raw
    /// occurrence count, never the score below, because the count is the fact and the score is
    /// only how results are ordered.
    pub count: u16,
    /// **The ranking key**: `count` scaled by [`SCORE_SCALE`] and divided by the page's token
    /// count, so a short page where a term is dense outranks a long page where it is sparse even
    /// with a smaller raw count. Not exposed: nothing outside [`Ranked::offer`] needs to compare
    /// it, and printing a fixed-point ratio would need explaining that `count` does not.
    score: u32,
}

impl Found {
    /// **Where a reader can open this page**, as a name they can type: `<STORE_DIR>/<bundle>/<page>`.
    ///
    /// Computed by the searcher from the shard it opened, **not** read out of the index. That is
    /// deliberate and it is why no byte of the layout changed for this: the party doing the search
    /// already knows which bundle it is inside, so a shard that also carried the installed location
    /// would be storing a fact its only reader can derive, and storing it twice is a chance for the
    /// two to disagree.
    pub fn location(&self) -> &[u8] {
        &self.location[..self.location_len as usize]
    }

    /// Whether the location above lost its tail to [`LOCATION_MAX`].
    pub fn truncated(&self) -> bool {
        self.truncated
    }

    /// The page's title: its first level-one heading, or its path if it has none.
    pub fn title(&self) -> &[u8] {
        &self.title[..self.title_len as usize]
    }

    /// **Where the page came from**, as the index records it: a path in the source tree
    /// (`notes/pipes.md`), which is provenance rather than something to open. [`Found::location`]
    /// is the openable name.
    pub fn origin(&self) -> &[u8] {
        &self.origin[..self.origin_len as usize]
    }
}

/// **The merge across shards**: the best [`RESULTS_MAX`] results offered, strongest first.
///
/// The roadmap's "the index is a merge of shards" lives here, and it is a fixed array rather than a
/// heap because the merge runs in a shell holding one 4 KiB stack page and no allocator. Ties keep
/// the order they were offered in, so a store whose bundles are searched in manifest order gives
/// the same answer twice.
pub struct Ranked {
    found: [Found; RESULTS_MAX],
    n: usize,
    offered: usize,
}

impl Default for Ranked {
    fn default() -> Self {
        Ranked::new()
    }
}

impl Ranked {
    /// An empty table. `const` so a caller with no allocator can put one in `.bss`, which is what
    /// the shell does: [`RESULTS_MAX`] of these is about 2.4 KiB and a stack page is four.
    pub const fn new() -> Self {
        Ranked {
            found: [Found {
                location: [0; LOCATION_MAX],
                location_len: 0,
                truncated: false,
                title: [0; TITLE_MAX],
                title_len: 0,
                origin: [0; PATH_MAX],
                origin_len: 0,
                count: 0,
                score: 0,
            }; RESULTS_MAX],
            n: 0,
            offered: 0,
        }
    }

    /// Offer one page that mentioned the term. Kept if it beats the weakest result held.
    ///
    /// It takes the record's fields rather than a [`Page`], so the merge is independent of how
    /// the record was read: a caller with a path, a title and a token count in hand can offer
    /// one, which is what lets the shell's rendering be host-tested without a shard to open.
    ///
    /// `page_tokens` is the page's own [`Page::tokens`], the denominator `score` divides by. A
    /// page whose stored token count is zero (only possible for a version-1 layout this reader
    /// never opens, or an empty page) is treated as one, so a term cannot score as infinitely
    /// dense.
    pub fn offer(
        &mut self,
        bundle: &[u8],
        path: &[u8],
        title: &[u8],
        count: u16,
        page_tokens: u32,
    ) {
        self.offered += 1;
        let s = score(count, page_tokens);
        // Where it goes: past everything that scored at least as strongly, which keeps ties in
        // offer order because the test is strict.
        let mut at = 0;
        while at < self.n && self.found[at].score >= s {
            at += 1;
        }
        if at == RESULTS_MAX {
            return;
        }
        let end = (self.n + 1).min(RESULTS_MAX);
        for i in (at + 1..end).rev() {
            self.found[i] = self.found[i - 1];
        }
        self.n = end;

        let f = &mut self.found[at];
        f.count = count;
        f.score = s;
        (f.location_len, f.truncated) = location(bundle, path, &mut f.location);
        f.title_len = copy_into(&mut f.title, title) as u8;
        f.origin_len = copy_into(&mut f.origin, path) as u8;
    }

    /// The results, strongest first.
    pub fn results(&self) -> &[Found] {
        &self.found[..self.n]
    }

    /// **How many results were offered in total**, including the ones that did not fit. A caller
    /// that prints [`results`](Ranked::results) without this is implying its answer was complete.
    pub fn offered(&self) -> usize {
        self.offered
    }
}

/// **Search one shard**, offering every page that mentions `term` into `into`.
///
/// This is the single point at which the writer and the reader are proved to agree, and it is why
/// it lives here rather than in either caller: `cargo xtask manual <term>` on the host and the
/// shell's `apropos` at the prompt run **this function**, over the same bytes, through the same
/// one-page-at-a-time [`Pages`]. Only the IO differs.
///
/// A term nothing mentions is `Ok(())` with nothing offered, because "no page says that" is an
/// answer rather than a failure. An [`Err`] means the shard is not one.
///
/// # Memory
///
/// Constant, and small: one page buffer at a time inside [`lookup`], [`postings`] and
/// [`page_record`], never two, plus a sixteen-posting batch on this frame. A term mentioned by more
/// pages than that is read in batches rather than needing a bigger array.
pub fn search(
    bundle: &[u8],
    term: &[u8],
    src: &mut impl Pages,
    into: &mut Ranked,
) -> Result<(), Error> {
    let mut first = [0u8; PAGE];
    if !src.page(0, &mut first) {
        return Err(Error::Truncated);
    }
    let h = Header::parse(&first)?;
    let Some(hit) = lookup(&h, term, src) else {
        return Ok(());
    };

    let mut batch = [Posting { page: 0, count: 0 }; 16];
    let mut done = 0u32;
    while done < hit.count as u32 {
        let rest = Hit {
            first: hit.first + done,
            count: (hit.count as u32 - done) as u16,
        };
        let n = postings(&h, &rest, src, &mut batch);
        if n == 0 {
            break;
        }
        for p in &batch[..n] {
            if let Some(rec) = page_record(&h, p.page, src) {
                into.offer(bundle, rec.path(), rec.title(), p.count, rec.tokens());
            }
        }
        done += n as u32;
    }
    Ok(())
}

/// Build `<STORE_DIR>/<bundle>/<basename of path>` into `out`, returning its length and whether it
/// lost its tail.
fn location(bundle: &[u8], path: &[u8], out: &mut [u8; LOCATION_MAX]) -> (u8, bool) {
    let base = match path.iter().rposition(|&b| b == b'/') {
        Some(i) => &path[i + 1..],
        None => path,
    };
    let mut n = 0usize;
    let mut put = |bytes: &[u8]| {
        for &b in bytes {
            if n < LOCATION_MAX {
                out[n] = b;
                n += 1;
            }
        }
    };
    put(STORE_DIR.as_bytes());
    put(b"/");
    put(bundle);
    put(b"/");
    put(base);
    let want = STORE_DIR.len() + 1 + bundle.len() + 1 + base.len();
    (n as u8, want > LOCATION_MAX)
}

/// Copy as much of `src` as fits, returning how much that was.
fn copy_into(dst: &mut [u8], src: &[u8]) -> usize {
    let n = src.len().min(dst.len());
    dst[..n].copy_from_slice(&src[..n]);
    dst[n..].fill(0);
    n
}

/// Compare a term record's term against a key.
fn cmp(rec: &[u8], key: &[u8]) -> core::cmp::Ordering {
    let n = rec[TERM_MAX + 6] as usize;
    rec[..n.min(TERM_MAX)].cmp(key)
}

fn u16v(b: &[u8], at: usize) -> u16 {
    u16::from_le_bytes([b[at], b[at + 1]])
}

fn u32(b: &[u8], at: usize) -> u32 {
    u32::from_le_bytes([b[at], b[at + 1], b[at + 2], b[at + 3]])
}

fn u64v(b: &[u8], at: usize) -> u64 {
    let mut v = [0u8; 8];
    v.copy_from_slice(&b[at..at + 8]);
    u64::from_le_bytes(v)
}

// ---- the builder, host only ----------------------------------------------------------------

#[cfg(feature = "builder")]
mod builder {
    use alloc::collections::BTreeMap;
    use alloc::vec;
    use alloc::vec::Vec;

    use super::*;

    /// One page offered to the builder.
    pub struct Source<'a> {
        /// The path the store will know the page by. Truncated to [`PATH_MAX`].
        pub path: &'a str,
        /// The page's title. Truncated to [`TITLE_MAX`].
        pub title: &'a str,
        /// The page's markdown source, which is what gets tokenised.
        pub text: &'a [u8],
    }

    /// Build an index over these pages.
    ///
    /// This is the only allocating function in the crate and it is behind the `builder` feature for
    /// that reason: it runs in `xtask` on a host with a heap, never on the guest.
    ///
    /// # EXAMPLES
    ///
    /// ```
    /// use manual::index;
    ///
    /// let bytes = index::build(&[
    ///     index::Source { path: "notes/glob.md", title: "Globbing", text: b"a pattern and a name" },
    ///     index::Source { path: "notes/ipc.md", title: "IPC", text: b"a name and an endpoint" },
    /// ]);
    ///
    /// let mut src = index::Slice(&bytes);
    /// let h = index::Header::parse(&bytes[..index::PAGE]).unwrap();
    ///
    /// // Both pages say "name", so the term has two postings.
    /// let hit = index::lookup(&h, b"name", &mut src).unwrap();
    /// assert_eq!(hit.count, 2);
    ///
    /// // And one of them is the one whose title says so.
    /// let mut post = [index::Posting { page: 0, count: 0 }; 4];
    /// let n = index::postings(&h, &hit, &mut src, &mut post);
    /// let first = index::page_record(&h, post[0].page, &mut src).unwrap();
    /// assert_eq!(n, 2);
    /// assert_eq!(first.title(), b"Globbing");
    /// ```
    pub fn build(pages: &[Source<'_>]) -> Vec<u8> {
        // term -> (page index -> occurrences). A BTreeMap because the term table must come out
        // sorted and this way it is sorted by construction rather than by a pass nobody can see.
        let mut terms: BTreeMap<Vec<u8>, BTreeMap<u16, u32>> = BTreeMap::new();
        // Every page's total token count, the ranking denominator: not the distinct-term count
        // above, the count of every token `tokens` ever called `f` with for that page, underscore
        // joins included, because that is the same population `count` is drawn from.
        let mut page_tokens = vec![0u32; pages.len()];
        for (i, p) in pages.iter().enumerate() {
            tokens(p.text, |t| {
                page_tokens[i] = page_tokens[i].saturating_add(1);
                *terms
                    .entry(t.to_vec())
                    .or_default()
                    .entry(i as u16)
                    .or_default() += 1;
            });
        }

        let post_count: usize = terms.values().map(|m| m.len()).sum();
        let page_off = PAGE;
        let term_off = page_off + round_up(pages.len() * PAGE_REC);
        let post_off = term_off + round_up(terms.len() * TERM_REC);
        let total = post_off + round_up(post_count * POST_REC);
        let mut out = vec![0u8; total];

        out[..8].copy_from_slice(&MAGIC);
        out[8..12].copy_from_slice(&VERSION.to_le_bytes());
        out[12..16].copy_from_slice(&(pages.len() as u32).to_le_bytes());
        out[16..20].copy_from_slice(&(terms.len() as u32).to_le_bytes());
        out[20..24].copy_from_slice(&(post_count as u32).to_le_bytes());
        out[24..32].copy_from_slice(&(page_off as u64).to_le_bytes());
        out[32..40].copy_from_slice(&(term_off as u64).to_le_bytes());
        out[40..48].copy_from_slice(&(post_off as u64).to_le_bytes());
        out[48..56].copy_from_slice(&(total as u64).to_le_bytes());

        for (i, p) in pages.iter().enumerate() {
            let rec = page_off + i * PAGE_REC;
            let path = p.path.as_bytes();
            let n = path.len().min(PATH_MAX);
            out[rec..rec + n].copy_from_slice(&path[..n]);
            let title = p.title.as_bytes();
            let m = title.len().min(TITLE_MAX);
            out[rec + PATH_MAX..rec + PATH_MAX + m].copy_from_slice(&title[..m]);
            out[rec + PATH_MAX + TITLE_MAX] = n as u8;
            out[rec + PATH_MAX + TITLE_MAX + 1] = m as u8;
            out[rec + PATH_MAX + TITLE_MAX + 2..rec + PATH_MAX + TITLE_MAX + 6]
                .copy_from_slice(&page_tokens[i].to_le_bytes());
        }

        let mut post = 0usize;
        for (i, (term, byname)) in terms.iter().enumerate() {
            let rec = term_off + i * TERM_REC;
            let n = term.len().min(TERM_MAX);
            out[rec..rec + n].copy_from_slice(&term[..n]);
            out[rec + TERM_MAX..rec + TERM_MAX + 4].copy_from_slice(&(post as u32).to_le_bytes());
            out[rec + TERM_MAX + 4..rec + TERM_MAX + 6]
                .copy_from_slice(&(byname.len() as u16).to_le_bytes());
            out[rec + TERM_MAX + 6] = n as u8;
            for (page, count) in byname {
                let at = post_off + post * POST_REC;
                out[at..at + 2].copy_from_slice(&page.to_le_bytes());
                out[at + 2..at + 4]
                    .copy_from_slice(&(*count).min(u16::MAX as u32).to_le_bytes()[..2]);
                post += 1;
            }
        }

        out
    }

    /// The first level-one heading in a markdown document, which is what a page is called.
    pub fn title_of(text: &[u8]) -> Option<&str> {
        let mut start = 0;
        while start < text.len() {
            let end = text[start..]
                .iter()
                .position(|&b| b == b'\n')
                .map(|k| start + k)
                .unwrap_or(text.len());
            let line = &text[start..end];
            if line.starts_with(b"# ") {
                return core::str::from_utf8(&line[2..]).ok().map(str::trim);
            }
            start = end + 1;
        }
        None
    }

    fn round_up(n: usize) -> usize {
        n.div_ceil(PAGE) * PAGE
    }
}

#[cfg(feature = "builder")]
pub use builder::{Source, build, title_of};

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_query_folds_the_way_the_text_did() {
        // The one property that makes a lookup possible at all: the builder's tokeniser and the
        // reader's query normaliser must agree, byte for byte, on what a term is.
        let mut buf = [0u8; TERM_MAX];
        let n = normalize(b"Capability!", &mut buf);
        assert_eq!(&buf[..n], b"capability");

        let mut seen: [[u8; TERM_MAX]; 4] = [[0; TERM_MAX]; 4];
        let mut lens = [0usize; 4];
        let mut i = 0;
        tokens(b"Capability, a `Frame`. x", |t| {
            if i < 4 {
                seen[i][..t.len()].copy_from_slice(t);
                lens[i] = t.len();
                i += 1;
            }
        });
        // Two terms out of four words: `a` and `x` are single characters, and a per-letter posting
        // list answers no question anybody asks a manual.
        assert_eq!(i, 2);
        assert_eq!(&seen[0][..lens[0]], b"capability");
        assert_eq!(&seen[1][..lens[1]], b"frame");
    }

    #[test]
    fn an_underscore_name_is_searchable_as_itself() {
        // **The case the test above asserted and did not check.** `normalize` drops every
        // non-alphanumeric byte, so a reader typing `line_editor` looks up `lineeditor`; until
        // 2026-08-18 the tokeniser only ever wrote `line` and `editor`, so that lookup could not
        // match however many pages said the name. In a repository whose prose is full of
        // `snake_case` identifiers, that is most of what anybody would search for.
        let mut key = [0u8; TERM_MAX];
        let n = normalize(b"line_editor", &mut key);
        assert_eq!(&key[..n], b"lineeditor");

        let mut seen: [[u8; TERM_MAX]; 8] = [[0; TERM_MAX]; 8];
        let mut lens = [0usize; 8];
        let mut i = 0;
        tokens(b"the line_editor crate", |t| {
            if i < 8 {
                seen[i][..t.len()].copy_from_slice(t);
                lens[i] = t.len();
                i += 1;
            }
        });
        // No `alloc` here: this module compiles without it on the guest path, so the check is a
        // closure over the fixed array rather than a `Vec`.
        let has = |want: &[u8]| (0..i).any(|k| &seen[k][..lens[k]] == want);
        let count = |want: &[u8]| (0..i).filter(|&k| &seen[k][..lens[k]] == want).count();
        assert!(has(b"lineeditor"));
        // The halves are still terms of their own, so `apropos editor` keeps working.
        assert!(has(b"line"));
        assert!(has(b"editor"));
        // And an ordinary word is not offered twice, which is what keeps the term table from
        // doubling over prose that has no underscores in it.
        assert_eq!(count(b"crate"), 1);
    }

    #[test]
    fn a_term_longer_than_the_record_folds_to_its_prefix() {
        let long = b"averyveryverylongidentifiername";
        let mut buf = [0u8; TERM_MAX];
        assert_eq!(normalize(long, &mut buf), TERM_MAX);
    }

    #[test]
    fn a_header_that_is_not_one_is_refused() {
        assert_eq!(Header::parse(&[0u8; 64]), Err(Error::BadMagic));
        assert_eq!(Header::parse(&[0u8; 8]), Err(Error::Truncated));
    }

    #[test]
    fn a_shard_from_another_version_is_refused_rather_than_read() {
        // The field the builder has always written and nothing read until phase 2. A reader that
        // ignored it would go on to binary-search a term table whose record size it is guessing.
        let mut first = [0u8; 64];
        first[..8].copy_from_slice(&MAGIC);
        first[8..12].copy_from_slice(&VERSION.to_le_bytes());
        assert!(Header::parse(&first).is_ok());
        first[8..12].copy_from_slice(&(VERSION + 1).to_le_bytes());
        assert_eq!(
            Header::parse(&first),
            Err(Error::BadVersion { found: VERSION + 1 })
        );
    }

    #[test]
    fn the_manifest_is_one_bundle_per_line() {
        let mut seen = [[0u8; 8]; 4];
        let mut lens = [0usize; 4];
        let mut i = 0;
        // A blank line and a stray carriage return, because the manifest is a text file a person
        // may have opened.
        bundles(b"manual\r\nswish\n\nglob\n", |b| {
            if i < 4 {
                seen[i][..b.len()].copy_from_slice(b);
                lens[i] = b.len();
                i += 1;
            }
        });
        assert_eq!(i, 3);
        assert_eq!(&seen[0][..lens[0]], b"manual");
        assert_eq!(&seen[1][..lens[1]], b"swish");
        assert_eq!(&seen[2][..lens[2]], b"glob");
    }

    #[cfg(feature = "builder")]
    #[test]
    fn every_term_the_builder_wrote_is_found_by_the_reader() {
        use alloc::vec::Vec;

        // Enough terms to make the term table span several pages, because the binary search over
        // pages is the part that a single-page index would never exercise. `TERM_REC` is 32 bytes
        // and a page holds 128 records, so this is four pages of terms.
        let mut text = alloc::string::String::new();
        let mut want: Vec<alloc::string::String> = Vec::new();
        for i in 0..500 {
            let t = alloc::format!("term{i:04}");
            text.push_str(&t);
            text.push(' ');
            want.push(t);
        }
        let bytes = build(&[Source {
            path: "notes/x.md",
            title: "X",
            text: text.as_bytes(),
        }]);
        let h = Header::parse(&bytes[..PAGE]).unwrap();
        assert_eq!(h.terms as usize, want.len());

        let mut src = Slice(&bytes);
        for t in &want {
            let hit = lookup(&h, t.as_bytes(), &mut src)
                .unwrap_or_else(|| panic!("the reader cannot find {t}, which the builder wrote"));
            assert_eq!(hit.count, 1);
        }
        assert!(lookup(&h, b"absent", &mut src).is_none());
    }

    #[cfg(feature = "builder")]
    #[test]
    fn a_record_never_straddles_a_page() {
        // The property the whole layout exists for: a reader that holds one page never sees half a
        // record. It is a claim about the offsets, so it is checked on the offsets.
        let bytes = build(&[Source {
            path: "a",
            title: "A",
            text: b"one two three",
        }]);
        let h = Header::parse(&bytes[..PAGE]).unwrap();
        for off in [h.page_off, h.term_off, h.post_off] {
            assert_eq!(off % PAGE as u64, 0, "section at {off} is not page aligned");
        }
        for rec in [PAGE_REC, TERM_REC, POST_REC] {
            assert_eq!(PAGE % rec, 0, "{rec}-byte records do not divide a page");
        }
        assert_eq!(h.total as usize, bytes.len());
    }

    #[cfg(feature = "builder")]
    #[test]
    fn a_search_merges_two_shards_and_ranks_them_by_count() {
        // Two bundles, as the store really has: each is built and searched on its own, and the
        // answer is the merge. This is the roadmap's "the index is a merge of shards", and it is
        // also the property that makes installing a component make its documentation searchable
        // without a reindex pass.
        let swish = build(&[Source {
            path: "notes/pipes.md",
            title: "Pipes and redirection",
            text: b"capability capability capability pipe",
        }]);
        let glob = build(&[Source {
            path: "notes/glob.md",
            title: "The glob matcher",
            text: b"capability pattern",
        }]);

        let mut r = Ranked::new();
        search(b"swish", b"capability", &mut Slice(&swish), &mut r).unwrap();
        search(b"glob", b"capability", &mut Slice(&glob), &mut r).unwrap();

        let out = r.results();
        assert_eq!(out.len(), 2);
        assert_eq!(r.offered(), 2);
        // Strongest first, across shards, and the shard searched second wins because it matched
        // more strongly. A merge that just concatenated would answer in manifest order.
        assert_eq!(out[0].count, 3);
        assert_eq!(out[0].title(), b"Pipes and redirection");
        // **The name a reader can type**, derived from the shard the searcher opened rather than
        // read out of it, so no byte of the layout carries it.
        assert_eq!(out[0].location(), b"doc/swish/pipes.md");
        // And the provenance, which is what the index does store.
        assert_eq!(out[0].origin(), b"notes/pipes.md");
        assert_eq!(out[1].count, 1);
        assert_eq!(out[1].location(), b"doc/glob/glob.md");

        // A term no page says is an answer, not a failure.
        let mut none = Ranked::new();
        search(b"glob", b"unmentioned", &mut Slice(&glob), &mut none).unwrap();
        assert_eq!(none.results().len(), 0);
        assert_eq!(none.offered(), 0);
    }

    #[cfg(feature = "builder")]
    #[test]
    fn a_search_keeps_the_best_sixteen_and_counts_the_rest() {
        // The bound that lets the shell run this in `.bss`: more matching pages than the table
        // holds, kept in count order, with the total still reported so the caller does not imply a
        // complete answer.
        use alloc::string::String;
        use alloc::vec::Vec;

        let mut texts: Vec<String> = Vec::new();
        for i in 0..RESULTS_MAX + 5 {
            let mut t = String::new();
            for _ in 0..=i {
                t.push_str("capability ");
            }
            // One word of filler, the same on every page, so density (not just raw count) still
            // increases with `i`: without it every page here is *only* the search term, so every
            // page's density is 1.0 and this test would be asserting a tie-break order rather than
            // the thing it says it asserts.
            t.push_str("noise");
            texts.push(t);
        }
        let paths: Vec<String> = (0..texts.len())
            .map(|i| alloc::format!("p{i}.md"))
            .collect();
        let sources: Vec<Source<'_>> = texts
            .iter()
            .zip(&paths)
            .map(|(t, p)| Source {
                path: p,
                title: "page",
                text: t.as_bytes(),
            })
            .collect();
        let bytes = build(&sources);

        let mut r = Ranked::new();
        search(b"many", b"capability", &mut Slice(&bytes), &mut r).unwrap();
        assert_eq!(r.results().len(), RESULTS_MAX);
        assert_eq!(r.offered(), RESULTS_MAX + 5);
        // Sorted by score, and here that agrees with raw count by construction (both grow with
        // `i`), so the strongest page is still the one with the most occurrences.
        assert_eq!(r.results()[0].count as usize, texts.len());
        for pair in r.results().windows(2) {
            assert!(pair[0].count >= pair[1].count, "the merge is not sorted");
        }
    }

    #[cfg(feature = "builder")]
    #[test]
    fn ranking_divides_by_page_length() {
        // The property `notes/manual.md`'s "where this goes next" named and priced: a short page
        // where a term is dense outranks a long page where the same term is only mentioned in
        // passing, even though the long page's raw occurrence count is higher.
        let short = build(&[Source {
            path: "short.md",
            title: "Short",
            // Two tokens, one of them the term: as dense as a page can be without being nothing
            // else.
            text: b"capability page",
        }]);
        let mut long_text = alloc::string::String::new();
        for _ in 0..99 {
            long_text.push_str("filler ");
        }
        // Three mentions, but buried in ninety-nine words of filler: a higher raw count than the
        // short page's one, and a much lower density.
        long_text.push_str("capability capability capability");
        let long = build(&[Source {
            path: "long.md",
            title: "Long",
            text: long_text.as_bytes(),
        }]);

        let mut r = Ranked::new();
        search(b"a", b"capability", &mut Slice(&short), &mut r).unwrap();
        search(b"b", b"capability", &mut Slice(&long), &mut r).unwrap();

        let out = r.results();
        assert_eq!(out.len(), 2);
        // The raw counts are honest and unchanged: three mentions is still reported as three.
        let short_found = out
            .iter()
            .find(|f| f.location() == b"doc/a/short.md")
            .unwrap();
        let long_found = out
            .iter()
            .find(|f| f.location() == b"doc/b/long.md")
            .unwrap();
        assert_eq!(short_found.count, 1);
        assert_eq!(long_found.count, 3);
        // But density, not raw count, decides the order: the short page comes first.
        assert_eq!(out[0].location(), b"doc/a/short.md");
        assert_eq!(out[1].location(), b"doc/b/long.md");
    }

    #[cfg(feature = "builder")]
    #[test]
    fn a_title_is_the_first_level_one_heading() {
        assert_eq!(
            title_of(b"intro\n\n# The title\n\n## no\n"),
            Some("The title")
        );
        assert_eq!(title_of(b"## only a section\n"), None);
    }
}
