//! **Measured boot: the hash the kernel checks init against** (milestone 22 phase B.1).
//!
//! The kernel's promise is "a verified core that confines unverified workloads" (DECISIONS §14).
//! init is the unverified component that builds every other process, and until this crate existed
//! its *bytes* were loaded on trust: whatever the bootloader put in RAM at
//! `/chosen/linux,initrd-start` got parsed and entered. This closes that gap. The kernel carries a
//! **trust root** compiled into its own image (a list of `(name, digest)` pairs generated by the
//! build, see `kernel/build.rs`), hashes the archive entry it is about to load, and refuses to
//! enter userspace on a mismatch. "This kernel runs exactly this init," enforced.
//!
//! **Why SHA-256, hand-written.** The threat is an attacker who can substitute the initrd bytes, so
//! the hash must be collision- and preimage-resistant; a fast non-crypto hash (the FNV that xtask
//! uses to notice stale build inputs) would let someone craft a colliding init. Among the
//! collision-resistant options SHA-256 is the one that costs the trusted computing base least:
//! about a hundred lines of shifts and adds with no dependency, no allocation, and no unsafe, and
//! it is checkable by hand against `shasum -a 256` on any host on earth. BLAKE3 is faster and
//! Ed25519-signed images are the richer story (both recorded in DECISIONS §22 as the follow-up),
//! but both are more code inside the boundary we are trying to keep small. Speed is not the
//! constraint: this runs once, over a few hundred kilobytes, before the first user instruction.
//!
//! **One implementation, both sides.** The build (xtask, on the host) and the kernel (`no_std`, at
//! boot) hash through *this* crate, so there is exactly one definition of the measurement and no
//! chance of a host/target disagreement quietly turning into a boot failure. That is the same
//! discipline `nifefs` gets: one parser for the archive whether it is on a disk or in RAM. The
//! risk it trades for is a buggy implementation agreeing with itself, which is why the tests below
//! are the published FIPS 180-4 vectors and not self-consistency checks.
//!
//! See notes/trusted-init.md and DECISIONS §22.
//!
//! # Examples
//!
//! ```
//! use measured_boot::sha256;
//!
//! // The FIPS 180-4 vector for "abc", which is what pins this implementation.
//! let d = sha256(b"abc");
//! assert_eq!(
//!     d[..4],
//!     [0xba, 0x78, 0x16, 0xbf],
//! );
//! // The empty input is the other classic vector, and the one an off-by-one padding bug fails.
//! assert_eq!(sha256(b"")[..4], [0xe3, 0xb0, 0xc4, 0x42]);
//! ```
//!
//! Verification is a lookup by name and a comparison, and the two ways it can fail are distinct
//! on purpose: a component nobody measured is a different problem from one that changed.
//!
//! ```
//! use measured_boot::{Measurement, sha256, verify, VerifyError};
//!
//! let root = [Measurement { name: "init", digest: sha256(b"the real init") }];
//!
//! assert!(verify(&root, "init", b"the real init").is_ok());
//! assert_eq!(verify(&root, "init", b"a tampered init"), Err(VerifyError::Mismatch));
//!
//! // A name the trust root says nothing about is a REFUSAL, not a pass. An empty or stale root
//! // must fail closed, or the check evaporates the first time someone skips the build step that
//! // fills it in.
//! assert_eq!(verify(&root, "stowaway", b"anything"), Err(VerifyError::Unmeasured));
//! assert_eq!(verify(&[], "init", b"the real init"), Err(VerifyError::Unmeasured));
//! ```
//!
//! Name: ratified 2026-08-01 (calef, milestone 63), replacing `measure`. Refused `measure` (a verb,
//! and generic enough to name almost anything). "Measured boot" is the standard term for boot-time
//! hashing, so the new name also buys the recognition a reader arrives with.

#![no_std]
// milestone 68's doc ratchet: every public item in this crate is documented, and
// `script/lint`'s -D warnings keeps it that way. See notes/doc-coverage.md for the
// crates that are not there yet.
#![warn(missing_docs)]

// The crate is `no_std` because the kernel links it. Its tests run on the host and want `Vec` and
// `String` to build tampered inputs, so the test build pulls `std` back in explicitly.
#[cfg(test)]
extern crate std;

/// A SHA-256 digest: 32 bytes.
pub const DIGEST_LEN: usize = 32;

/// The measurement of a program's bytes.
pub type Digest = [u8; DIGEST_LEN];

/// The round constants of SHA-256 (FIPS 180-4 §4.2.2): the first 32 bits of the fractional parts of
/// the cube roots of the first 64 primes.
const K: [u32; 64] = [
    0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
    0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
    0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
    0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
    0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
    0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
    0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
    0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2,
];

/// The initial hash value (FIPS 180-4 §5.3.3): the fractional parts of the square roots of the
/// first eight primes.
const H0: [u32; 8] = [
    0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, 0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19,
];

/// A streaming SHA-256. Streaming rather than one-shot because the kernel hashes a mapped region it
/// must not copy (there is no heap to copy a 300 KiB ELF into), and because a test can hash "the
/// real bytes with one byte flipped" without allocating a mutated copy.
#[derive(Clone)]
pub struct Sha256 {
    /// The eight working hash words.
    h: [u32; 8],
    /// Bytes not yet part of a full 64-byte block.
    block: [u8; 64],
    /// How many bytes of `block` are filled.
    filled: usize,
    /// Total message length in bytes; the padding encodes it in bits.
    len: u64,
}

impl Default for Sha256 {
    fn default() -> Self {
        Self::new()
    }
}

impl Sha256 {
    /// The initial state: `H0` loaded, no bytes absorbed yet.
    pub const fn new() -> Self {
        Self {
            h: H0,
            block: [0; 64],
            filled: 0,
            len: 0,
        }
    }

    /// Absorb more of the message. Call as many times as you like; the result depends only on the
    /// concatenation, which is what lets the kernel hash a region page by page.
    pub fn update(&mut self, mut bytes: &[u8]) {
        self.len = self.len.wrapping_add(bytes.len() as u64);
        while !bytes.is_empty() {
            let want = 64 - self.filled;
            let take = if bytes.len() < want {
                bytes.len()
            } else {
                want
            };
            self.block[self.filled..self.filled + take].copy_from_slice(&bytes[..take]);
            self.filled += take;
            bytes = &bytes[take..];
            if self.filled == 64 {
                let block = self.block;
                self.compress(&block);
                self.filled = 0;
            }
        }
    }

    /// Pad, absorb the length, and produce the digest (FIPS 180-4 §5.1.1: a `0x80` byte, zeros, then
    /// the 64-bit big-endian bit length).
    pub fn finalize(mut self) -> Digest {
        let bits = self.len.wrapping_mul(8);
        self.update(&[0x80]);
        // `update` just bumped `len`, but from here we only care about `filled`.
        while self.filled != 56 {
            self.update(&[0]);
        }
        // The bit length goes in directly, not through `update`, so the recursion ends here.
        self.block[56..64].copy_from_slice(&bits.to_be_bytes());
        let block = self.block;
        self.compress(&block);

        let mut out = [0u8; DIGEST_LEN];
        for (i, word) in self.h.iter().enumerate() {
            out[i * 4..i * 4 + 4].copy_from_slice(&word.to_be_bytes());
        }
        out
    }

    /// One 64-byte block through the compression function (FIPS 180-4 §6.2.2).
    fn compress(&mut self, block: &[u8; 64]) {
        let mut w = [0u32; 64];
        for i in 0..16 {
            w[i] = u32::from_be_bytes([
                block[i * 4],
                block[i * 4 + 1],
                block[i * 4 + 2],
                block[i * 4 + 3],
            ]);
        }
        for i in 16..64 {
            let s0 = w[i - 15].rotate_right(7) ^ w[i - 15].rotate_right(18) ^ (w[i - 15] >> 3);
            let s1 = w[i - 2].rotate_right(17) ^ w[i - 2].rotate_right(19) ^ (w[i - 2] >> 10);
            w[i] = w[i - 16]
                .wrapping_add(s0)
                .wrapping_add(w[i - 7])
                .wrapping_add(s1);
        }

        let [mut a, mut b, mut c, mut d, mut e, mut f, mut g, mut h] = self.h;
        for i in 0..64 {
            let s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
            let ch = (e & f) ^ ((!e) & g);
            let t1 = h
                .wrapping_add(s1)
                .wrapping_add(ch)
                .wrapping_add(K[i])
                .wrapping_add(w[i]);
            let s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
            let maj = (a & b) ^ (a & c) ^ (b & c);
            let t2 = s0.wrapping_add(maj);

            h = g;
            g = f;
            f = e;
            e = d.wrapping_add(t1);
            d = c;
            c = b;
            b = a;
            a = t1.wrapping_add(t2);
        }
        for (dst, add) in self.h.iter_mut().zip([a, b, c, d, e, f, g, h]) {
            *dst = dst.wrapping_add(add);
        }
    }
}

/// The SHA-256 of one contiguous slice.
pub fn sha256(bytes: &[u8]) -> Digest {
    let mut h = Sha256::new();
    h.update(bytes);
    h.finalize()
}

/// One entry of a trust root: "the program called `name` must hash to `digest`."
///
/// The kernel's copy is generated into its image by `kernel/build.rs` from the archive the build
/// just packed, which is what makes the check mean "this kernel runs exactly this init" without any
/// key management. Names are the nifefs archive names (`"init"`, `"system_initializer"`).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Measurement {
    /// The nifefs archive name this digest was measured for (`"init"`, `"system_initializer"`).
    pub name: &'static str,
    /// The expected SHA-256 of the program's bytes.
    pub digest: Digest,
}

/// Why a program was refused.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum VerifyError {
    /// The trust root says nothing about a program by this name, so we cannot vouch for it. **This
    /// is a refusal, not a pass**: an empty or stale trust root must fail closed, or the whole check
    /// evaporates the first time someone builds the kernel without the build step that fills it in.
    Unmeasured,
    /// The bytes hashed to something other than what the trust root says they must.
    Mismatch,
}

/// The digest the trust root demands for `name`, if it names it at all.
pub fn expected(root: &[Measurement], name: &str) -> Option<Digest> {
    root.iter().find(|m| m.name == name).map(|m| m.digest)
}

/// Check an already-computed digest against the trust root.
///
/// Split out from [`verify`] so a test can measure deliberately-tampered bytes without copying them,
/// and so the kernel can hash a region in pieces. The comparison is a plain `==`: the expected value
/// is public (it is printed in the build output and sits in the kernel's `.rodata`), so there is no
/// secret for a timing side channel to leak.
pub fn verify_digest(root: &[Measurement], name: &str, digest: &Digest) -> Result<(), VerifyError> {
    match expected(root, name) {
        None => Err(VerifyError::Unmeasured),
        Some(want) if want == *digest => Ok(()),
        Some(_) => Err(VerifyError::Mismatch),
    }
}

/// Hash `bytes` and check them against the trust root's entry for `name`.
pub fn verify(root: &[Measurement], name: &str, bytes: &[u8]) -> Result<(), VerifyError> {
    verify_digest(root, name, &sha256(bytes))
}

/// A digest as 64 lowercase hex characters (ASCII). No allocation, so the kernel can print it in a
/// diagnostic and the build can write it into the manifest.
pub fn hex(digest: &Digest) -> [u8; DIGEST_LEN * 2] {
    const HEXDIGITS: &[u8; 16] = b"0123456789abcdef";
    let mut out = [0u8; DIGEST_LEN * 2];
    for (i, byte) in digest.iter().enumerate() {
        out[i * 2] = HEXDIGITS[(byte >> 4) as usize];
        out[i * 2 + 1] = HEXDIGITS[(byte & 0xf) as usize];
    }
    out
}

/// **The archive entry that carries init's measurement table** (milestone 104).
///
/// The kernel's trust root is compiled into the kernel image, which works because the kernel is not
/// in the archive it measures. init *is* in that archive, so its own table cannot be compiled into
/// it without building userspace twice. Instead the build packs the table as an ordinary archive
/// entry and the kernel's trust root names it, so the kernel vouches for the table exactly as it
/// vouches for init, and init's refusals are as trustworthy as init is. See notes/trusted-init.md.
///
/// Name: **provisional**. Under `nifefs`'s `NAME_LEN = 32` with room to spare.
pub const PROGRAM_MEASUREMENTS: &str = "program_measurements";

/// **The measurement manifest format**, one entry per line: a name, one space, 64 hex characters.
/// Blank lines and `#` comments are skipped. Written by `cargo xtask`, read by `kernel/build.rs`
/// (which turns it into [`Measurement`]s) and by init (which reads it out of the archive at boot and
/// cannot allocate, so this yields borrowed names and never builds a collection).
///
/// `Err(line)` is a line we could not parse, carrying the line itself so a caller can name it. A
/// caller that skips errors still fails closed, because a name it cannot parse is a name it will not
/// find, and an unfound name is [`VerifyError::Unmeasured`].
///
/// ```
/// use measured_boot::manifest_entries;
///
/// let text = "# a comment\n\
///             console e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\n\
///             \n\
///             oops not-a-digest\n";
/// let mut it = manifest_entries(text);
/// assert_eq!(it.next().unwrap().unwrap().0, "console");
/// assert_eq!(it.next().unwrap().unwrap_err(), "oops not-a-digest");
/// assert!(it.next().is_none());
/// ```
pub fn manifest_entries(text: &str) -> impl Iterator<Item = Result<(&str, Digest), &str>> {
    text.lines()
        .map(str::trim)
        .filter(|line| !line.is_empty() && !line.starts_with('#'))
        .map(|line| {
            let (name, hex) = line.split_once(' ').ok_or(line)?;
            let digest = parse_hex(hex.trim()).ok_or(line)?;
            Ok((name, digest))
        })
}

/// The digest a manifest demands for `name`, if it names it at all. The runtime counterpart of
/// [`expected`]: same question, asked of text read at boot rather than of a compiled-in table.
pub fn expected_in_manifest(text: &str, name: &str) -> Option<Digest> {
    manifest_entries(text)
        .flatten()
        .find(|(n, _)| *n == name)
        .map(|(_, d)| d)
}

/// Hash `bytes` and check them against a manifest's entry for `name`.
///
/// The lookup happens **before** the hash, deliberately: init runs this over every program it is
/// about to load, and a name the table does not mention is a refusal that costs nothing to reach.
/// The three verdicts are [`verify`]'s, including the one that matters most: a name the manifest
/// says nothing about is [`VerifyError::Unmeasured`], not a pass. A table that failed to generate,
/// or arrived as bytes we could not read as text, therefore vouches for nothing.
pub fn verify_in_manifest(text: &str, name: &str, bytes: &[u8]) -> Result<(), VerifyError> {
    match expected_in_manifest(text, name) {
        None => Err(VerifyError::Unmeasured),
        Some(want) if want == sha256(bytes) => Ok(()),
        Some(_) => Err(VerifyError::Mismatch),
    }
}

/// Parse 64 hex characters back into a digest. Used by `kernel/build.rs` to read the manifest the
/// build wrote; strict, because a manifest we cannot parse must not silently become an empty trust
/// root (see [`VerifyError::Unmeasured`]).
pub fn parse_hex(text: &str) -> Option<Digest> {
    let bytes = text.as_bytes();
    if bytes.len() != DIGEST_LEN * 2 {
        return None;
    }
    let nibble = |c: u8| match c {
        b'0'..=b'9' => Some(c - b'0'),
        b'a'..=b'f' => Some(c - b'a' + 10),
        b'A'..=b'F' => Some(c - b'A' + 10),
        _ => None,
    };
    let mut out = [0u8; DIGEST_LEN];
    for (i, slot) in out.iter_mut().enumerate() {
        *slot = (nibble(bytes[i * 2])? << 4) | nibble(bytes[i * 2 + 1])?;
    }
    Some(out)
}

#[cfg(test)]
mod tests {
    use std::string::ToString;
    use std::vec;
    use std::vec::Vec;

    use super::*;

    /// The published FIPS 180-4 / NIST CAVS vectors, **not** self-consistency checks. Both sides of
    /// the boot check hash through this one implementation, so an implementation that agreed only
    /// with itself would still boot happily while measuring nothing real. These three (and the
    /// multi-`update` case below) are what make the digest a SHA-256 rather than a private function.
    #[test]
    fn matches_the_published_sha256_vectors() {
        let hexed = |d: &Digest| {
            let h = hex(d);
            core::str::from_utf8(&h).unwrap().to_string()
        };
        assert_eq!(
            hexed(&sha256(b"")),
            "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
        );
        assert_eq!(
            hexed(&sha256(b"abc")),
            "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"
        );
        // 448 bits: the vector that exercises padding into a second block.
        assert_eq!(
            hexed(&sha256(
                b"abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq"
            )),
            "248d6a61d20638b8e5c026930c3e6039a33ce45964ff2167f6ecedd419db06c1"
        );
        // A million 'a's, streamed: the classic long-message vector, which is also the case that
        // catches a length counter that overflows or is fed in bits instead of bytes.
        let mut h = Sha256::new();
        for _ in 0..1000 {
            h.update(&[b'a'; 1000]);
        }
        assert_eq!(
            hexed(&h.finalize()),
            "cdc76e5c9914fb9281a1c7e284d73e67f1809a48a497200e046d39ccc7112cd0"
        );
    }

    /// Streaming must equal one-shot for any split, because the kernel hashes a mapped region in
    /// whatever chunks it has and the build hashes one contiguous buffer. If those disagreed the
    /// boot would fail on correct bytes, which is the worst kind of fail-closed.
    #[test]
    fn streaming_in_any_chunking_equals_one_shot() {
        let data: Vec<u8> = (0..300u32).map(|i| (i * 7) as u8).collect();
        let want = sha256(&data);
        for chunk in [1usize, 3, 55, 64, 65, 128, 299, 300] {
            let mut h = Sha256::new();
            for piece in data.chunks(chunk) {
                h.update(piece);
            }
            assert_eq!(h.finalize(), want, "chunking by {chunk} changed the digest");
        }
    }

    /// The three verdicts the boot path can get, including the one that matters most: a trust root
    /// that does not mention the program is a **refusal**. A kernel built without the measurement
    /// step must not boot an unmeasured init.
    #[test]
    fn verification_accepts_the_measured_bytes_and_refuses_everything_else() {
        let root = [Measurement {
            name: "init",
            digest: sha256(b"the real init"),
        }];
        assert_eq!(verify(&root, "init", b"the real init"), Ok(()));
        assert_eq!(
            verify(&root, "init", b"the real init!"),
            Err(VerifyError::Mismatch)
        );
        assert_eq!(
            verify(&root, "system_initializer", b"the real init"),
            Err(VerifyError::Unmeasured)
        );
        assert_eq!(
            verify(&[], "init", b"the real init"),
            Err(VerifyError::Unmeasured)
        );
    }

    /// A single flipped bit anywhere must change the digest. This is the property the whole
    /// milestone rests on: an attacker who rewrites one byte of init's code cannot keep the
    /// measurement.
    #[test]
    fn one_flipped_bit_changes_the_digest() {
        let mut data = vec![0u8; 200];
        for (i, b) in data.iter_mut().enumerate() {
            *b = i as u8;
        }
        let base = sha256(&data);
        for i in [0usize, 1, 63, 64, 100, 199] {
            let mut tampered = data.clone();
            tampered[i] ^= 1;
            assert_ne!(sha256(&tampered), base, "flipping byte {i} kept the digest");
        }
    }

    /// Hex out, hex in: the manifest the build writes must read back as the digest the kernel checks.
    #[test]
    fn hex_round_trips_and_rejects_malformed_text() {
        let d = sha256(b"round trip");
        let text = hex(&d);
        let text = core::str::from_utf8(&text).unwrap();
        assert_eq!(parse_hex(text), Some(d));
        assert_eq!(parse_hex("abc"), None, "a short string is not a digest");
        assert_eq!(
            parse_hex(&"g".repeat(64)),
            None,
            "non-hex characters must not parse as zeros"
        );
    }

    /// The manifest is the second link of the chain (milestone 104): the kernel vouches for this
    /// text, and init decides what to load from it. So the same three verdicts have to hold when
    /// the trust root is *text read at boot* rather than a table compiled into an image, and the
    /// `Unmeasured` one has to hold hardest: a table that failed to generate, or one whose line for
    /// a program is malformed, must refuse that program rather than wave it through.
    #[test]
    fn a_manifest_gives_the_same_three_verdicts_a_compiled_in_trust_root_does() {
        let console = b"the real console".as_slice();
        let hexed = hex(&sha256(console));
        let hexed = core::str::from_utf8(&hexed).unwrap();
        let text = std::format!("# generated by cargo xtask\nconsole {hexed}\nbroken deadbeef\n");

        assert_eq!(verify_in_manifest(&text, "console", console), Ok(()));
        assert_eq!(
            verify_in_manifest(&text, "console", b"a tampered console"),
            Err(VerifyError::Mismatch)
        );
        assert_eq!(
            verify_in_manifest(&text, "swish", console),
            Err(VerifyError::Unmeasured),
            "a name the table does not mention is a refusal"
        );
        assert_eq!(
            verify_in_manifest(&text, "broken", b"deadbeef"),
            Err(VerifyError::Unmeasured),
            "a malformed line must refuse its program, not vouch for it"
        );
        assert_eq!(
            verify_in_manifest("", "console", console),
            Err(VerifyError::Unmeasured),
            "an empty table vouches for nothing"
        );
    }

    /// The format has exactly one definition, and `kernel/build.rs` reads it through this iterator
    /// too. A `#` comment, a blank line and CRLF-ish trailing space all appear in files people edit
    /// or diff, so they are skipped rather than reported; anything else that does not parse is
    /// reported with the line, because the build turns that into a hard error.
    #[test]
    fn manifest_parsing_skips_comments_and_reports_the_line_it_could_not_read() {
        let d = hex(&sha256(b"x"));
        let d = core::str::from_utf8(&d).unwrap();
        let text = std::format!("# header\n\n  wc {d}  \nno-space-here\nshort ab\n");
        let got: Vec<Result<(&str, Digest), &str>> = manifest_entries(&text).collect();
        assert_eq!(got.len(), 3);
        assert_eq!(got[0].unwrap().0, "wc");
        assert_eq!(got[1].unwrap_err(), "no-space-here");
        assert_eq!(got[2].unwrap_err(), "short ab");
        assert_eq!(expected_in_manifest(&text, "wc"), Some(sha256(b"x")));
    }

    /// Uppercase hex is hex. Every other test round-trips through our own lowercase `to_hex`, so
    /// the `b'A'..=b'F'` arm (and its `+ 10` arithmetic) was dead in the suite (milestone 85), and
    /// a digest pasted from a tool that prints uppercase would have been refused.
    #[test]
    fn uppercase_hex_parses_to_the_same_digest() {
        let lower = "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad";
        let upper = lower.to_uppercase();
        assert_eq!(parse_hex(&upper), parse_hex(lower));
        assert_eq!(parse_hex(&upper).unwrap()[0], 0xBA);
    }
}
