#!/usr/bin/env python3
# The oracle for G5's next-occurrence arithmetic (milestone 129 (scheduled execution); notes/scheduled-execution/
# calendar-grammar-g5.md). Each rule below is written twice, independently: once as the G5 line
# `crates/timetable` parses, and once as the dateutil rrule it must mean, built here by hand from the
# note's RRULE table rather than from the parser. dateutil answers `after`, and the answers are
# checked in as rrule.txt, which `recurrence`'s host tests read. No crate depends on dateutil.
#
# Regenerate with:  python3 crates/timetable/oracle/rrule.py > crates/timetable/oracle/rrule.txt
# Needs python-dateutil (2.9.0 made the checked-in table).
#
# Name: provisional, minted 2026-09-26 (UTC) by milestone 129's lane. Naming is calef's.
from datetime import datetime, timedelta
from dateutil.rrule import rrule, DAILY, WEEKLY, MONTHLY, MO, TU, WE, TH, FR, SA, SU

WD = (MO, TU, WE, TH, FR)
D0 = datetime(2026, 1, 1)
FAR = D0  # dtstart for rules with no `starting`: before every sample

RULES = [
    ("every day at 02:00", dict(freq=DAILY, byhour=2, byminute=0)),
    ("every day at 09:00,21:00", dict(freq=DAILY, byhour=(9, 21), byminute=0)),
    ("every weekday at 09:00", dict(freq=WEEKLY, byweekday=WD, byhour=9, byminute=0)),
    ("every weekend at 10:00", dict(freq=WEEKLY, byweekday=(SA, SU), byhour=10, byminute=0)),
    ("every week on mon,thu at 08:00", dict(freq=WEEKLY, byweekday=(MO, TH), byhour=8, byminute=0)),
    ("every month on 1,15 at 00:00", dict(freq=MONTHLY, bymonthday=(1, 15), byhour=0, byminute=0)),
    ("every month on last day at 23:00", dict(freq=MONTHLY, bymonthday=-1, byhour=23, byminute=0)),
    ("every month on 2nd tue at 09:00", dict(freq=MONTHLY, byweekday=TU(2), byhour=9, byminute=0)),
    ("every month on last fri at 17:00", dict(freq=MONTHLY, byweekday=FR(-1), byhour=17, byminute=0)),
    ("every month on last weekday at 18:00",
     dict(freq=MONTHLY, byweekday=WD, bysetpos=-1, byhour=18, byminute=0)),
    ("every month on first weekday at 07:30",
     dict(freq=MONTHLY, byweekday=WD, bysetpos=1, byhour=7, byminute=30)),
    ("every month on 1 in jan,apr,jul,oct at 06:00",
     dict(freq=MONTHLY, bymonth=(1, 4, 7, 10), bymonthday=1, byhour=6, byminute=0)),
    ("every month on 15 in mar at 09:00", dict(freq=MONTHLY, bymonth=3, bymonthday=15, byhour=9, byminute=0)),
    ("every 2 weeks on mon starting 2026-10-05 at 08:00",
     dict(freq=WEEKLY, interval=2, byweekday=MO, byhour=8, byminute=0, dtstart=datetime(2026, 10, 5, 8, 0))),
    ("every 3 days starting 2026-10-01 at 04:00",
     dict(freq=DAILY, interval=3, byhour=4, byminute=0, dtstart=datetime(2026, 10, 1, 4, 0))),
    ("every 3 months on 1 starting 2026-10-01 at 00:00",
     dict(freq=MONTHLY, interval=3, bymonthday=1, byhour=0, byminute=0, dtstart=datetime(2026, 10, 1, 0, 0))),
    ("every weekday from 09:00 to 16:45 by 15m",
     dict(freq=WEEKLY, byweekday=WD, byhour=tuple(range(9, 17)), byminute=(0, 15, 30, 45))),
    ("every day from 00:05 to 22:05 by 120m",
     dict(freq=DAILY, byhour=tuple(range(0, 23, 2)), byminute=5)),
    ("every day through 2026-03-31 at 12:00",
     dict(freq=DAILY, byhour=12, byminute=0, until=datetime(2026, 3, 31, 23, 59, 59))),
    ("every 2 weeks on tue,sat starting 2026-01-06 through 2027-06-30 at 23:59",
     dict(freq=WEEKLY, interval=2, byweekday=(TU, SA), byhour=23, byminute=59,
          dtstart=datetime(2026, 1, 6, 23, 59), until=datetime(2027, 6, 30, 23, 59, 59))),
]


def samples():
    # Spread across three years, plus the edges that matter: month ends, leap day, a year end.
    out = [D0 + timedelta(days=d, hours=(d * 7) % 24, minutes=(d * 13) % 60) for d in range(1, 1100, 37)]
    for y, m, d, h, mi in [(2028, 2, 28, 23, 0), (2028, 2, 29, 17, 0), (2026, 12, 31, 23, 59),
                           (2027, 1, 31, 23, 0), (2026, 10, 5, 8, 0), (2026, 10, 5, 7, 59),
                           (2026, 3, 31, 12, 0), (2026, 9, 30, 18, 0), (2027, 6, 30, 23, 59)]:
        out.append(datetime(y, m, d, h, mi))
    return out


def iso(t):
    return "none" if t is None else t.strftime("%Y-%m-%dT%H:%M")


print("# Generated by crates/timetable/oracle/rrule.py; do not edit. line|after|next")
for line, kw in RULES:
    kw = dict(kw)
    kw.setdefault("dtstart", FAR)
    kw.setdefault("bysecond", 0)
    kw["wkst"] = MO
    rr = rrule(**kw)
    for a in samples():
        print(f"{line}|{iso(a)}|{iso(rr.after(a, inc=False))}")
