[package]
name = "watch"
version = "0.1.0"
edition = "2024"
license.workspace = true

[lints]
workspace = true

[dependencies]
abi = { version = "0.1.0", path = "../abi" }
ps = { version = "0.1.0", path = "../ps" }

[dev-dependencies]
video_terminal = { version = "0.1.0", path = "../video_terminal" }
