//! **The trust root: what the progenitor is allowed to be** (milestone 22 phase B.1, DECISIONS §22).
//!
//! The kernel loads exactly one program itself: the boot program, out of the initrd archive
//! (`"progenitor"`, on every architecture, since milestone 295 took `"builder"` off riscv64's and
//! `x86_64`'s lists). Everything else is the progenitor's to load. `"hello"` is in the root too and
//! is not a counter-example: `spawn_hello` enters it directly for milestone 19d's and 19e's
//! init roles, and [`require`] refuses an entry the root does not name, so the root grew rather
//! than the check being relaxed (`xtask`'s `boot_programs`).
//! That one load used to be pure trust: whatever bytes sat at `/chosen/linux,initrd-start` got
//! parsed and entered. Since a compromised progenitor can endow malicious children and deny the system it
//! was meant to start, and since milestone 16b closed the DMA window a device could have used to
//! rewrite the initrd *behind* a check, checking it is now both necessary and airtight.
//!
//! So: the build hashes the archive entry it packed and writes the digest into a manifest; the
//! kernel's `build.rs` compiles that manifest into [`TRUST_ROOT`] (below, generated into `OUT_DIR`);
//! and the boot path calls [`require`] before it enters userspace. The meaning is exactly "this
//! kernel image runs exactly this progenitor," which needs no keys, no certificate chain, and no
//! signature-verification code inside the trusted computing base. The signature variant (update the progenitor
//! without rebuilding the kernel, at the cost of putting Ed25519 in the TCB) is recorded as a
//! follow-up in DECISIONS §22, not built.
//!
//! **It fails closed in both directions.** Wrong bytes halt, and a *missing* measurement halts too
//! (`measured_boot::VerifyError::Unmeasured`): a kernel built without the manifest has an empty trust root,
//! and an empty trust root vouches for nothing. That is deliberate. The failure mode of a measured
//! boot must never be "measure nothing and continue."
//!
//! See notes/trusted-init.md.

// `TRUST_ROOT`, generated by `kernel/build.rs` from `target/init-measure-<arch>.txt`: the digests of
// the boot programs this kernel image was built against. Empty if the build did not run the
// measurement step, which `require` treats as a refusal.
include!(concat!(env!("OUT_DIR"), "/trust_root.rs"));

/// The digest the trust root demands for the boot program `name`, if it names it.
// Test-only today: the boot path calls `require`, which decides and halts. These two are the same
// decision without the halt, which is what a test can actually assert on.
#[cfg_attr(not(test), allow(dead_code))]
pub fn expected(name: &str) -> Option<measured_boot::Digest> {
    measured_boot::expected(TRUST_ROOT, name)
}

/// Measure `bytes` against the trust root's entry for `name`. The decision function, separated from
/// the halt so tests can ask it what it thinks without ending the run.
#[cfg_attr(not(test), allow(dead_code))]
pub fn verify(name: &str, bytes: &[u8]) -> Result<(), measured_boot::VerifyError> {
    measured_boot::verify(TRUST_ROOT, name, bytes)
}

/// **Measure an archive entry, or halt.** Called with the entry's bytes immediately before the
/// kernel builds the progenitor's address space and drops to EL0/U-mode at its entry.
///
/// Two entries reach it: the boot program itself, and (since milestone 104) the measurement table
/// the progenitor loads everything else against, through [`require_program_measurements`]. The wording of the
/// diagnostics is deliberately about *entries* rather than *programs*, because one of them is not a
/// program.
///
/// A mismatch is not recoverable and must not be recovered from: there is no second progenitor to fall
/// back to, and running the wrong one is precisely the thing being prevented. So this prints what it
/// expected, what it measured, and halts. Loudly, because a silent halt at boot is indistinguishable
/// from a hardware problem, and whoever hits this needs to know it was a *refusal*.
pub fn require(name: &str, bytes: &[u8]) {
    let measured = measured_boot::sha256(bytes);
    match measured_boot::verify_digest(TRUST_ROOT, name, &measured) {
        Ok(()) => {}
        Err(measured_boot::VerifyError::Unmeasured) => {
            crate::println!();
            crate::println!(
                "  MEASURED BOOT REFUSED: no measurement for the archive entry '{name}'"
            );
            crate::println!("    measured sha256 {}", Hex(&measured));
            crate::println!(
                "    this kernel image carries {} measurement(s); it was built without the",
                TRUST_ROOT.len()
            );
            crate::println!("    build's measurement step, so it can vouch for nothing.");
            crate::println!("  halting rather than handing the archive to the progenitor.");
            crate::arch::halt();
        }
        Err(measured_boot::VerifyError::Mismatch) => {
            crate::println!();
            crate::println!(
                "  MEASURED BOOT REFUSED: '{name}' is not what this kernel image was built against"
            );
            if let Some(want) = measured_boot::expected(TRUST_ROOT, name) {
                crate::println!("    expected sha256 {}", Hex(&want));
            }
            crate::println!("    measured sha256 {}", Hex(&measured));
            crate::println!("  halting rather than handing the archive to the progenitor.");
            crate::arch::halt();
        }
    }
}

/// **Vouch for the table the progenitor measures its own loads against** (milestone 104), which is the whole
/// of the kernel's part in extending the chain past the progenitor.
///
/// The kernel loads one program and measures it. Everything else in the archive is the progenitor's to load,
/// and until this existed those bytes were unchecked, so the chain of trust stopped at the progenitor's entry.
/// The fix belongs in userspace (the progenitor decides what to do about a mismatch, the same way §26's
/// supervisor decides what to do about a fault), and it needs exactly one thing from here: a table
/// the progenitor can trust as much as the kernel trusts the progenitor.
///
/// **Why the kernel measures a file it never reads.** The progenitor's own table cannot be compiled into the progenitor,
/// because the progenitor is *in* the archive it would be measuring; generating it would mean building
/// userspace twice with an invariant holding the chain up. So the build packs the table as an
/// ordinary archive entry, [`measured_boot::PROGRAM_MEASUREMENTS`], and this hashes it beside the progenitor.
/// Nothing here parses it or acts on it: the kernel gains one digest in its trust root and no
/// policy at all, which is the line DECISIONS §26 draws and notes/trusted-init.md's rejected
/// alternative (hashing the whole 14 MB archive in the kernel) crosses.
///
/// A **missing** table halts, for [`require`]'s reason one level down: a progenitor that cannot vouch for
/// what it loads must not be handed the archive at all.
pub fn require_program_measurements(fs: &nifefs::Fs<'_>) {
    let name = measured_boot::PROGRAM_MEASUREMENTS;
    match fs.read(name) {
        Some(bytes) => require(name, bytes),
        None => {
            crate::println!();
            crate::println!("  MEASURED BOOT REFUSED: the archive carries no '{name}' table");
            crate::println!(
                "    the progenitor could not vouch for anything it loads, so it is not started."
            );
            crate::println!("  halting rather than entering a progenitor that measures nothing.");
            crate::arch::halt();
        }
    }
}

/// **Load one archive program the way the progenitor would have: only if the chain vouches for it**
/// (milestone 563 (a seal check that reads bytes cannot see a check that was dropped)).
///
/// A soak, job-mix, bench or disk-throughput boot replaces the hand-over with its own workload, so
/// nothing ever calls [`require`] and the progenitor never measures anything. Until this existed
/// such a boot entered archive programs nobody had checked, and a release build dropped
/// [`TRUST_ROOT`] as dead code, so `uefi_loader`'s build refused every soak kernel for xenon's stick
/// as `NOT SEALED` and `script/board-image --soak` printed the same false alarm for radon. This is
/// the chain an ordinary boot runs, two links long: [`require_program_measurements`] vouches for the
/// archive's measurement table against this kernel image, and the table vouches for `name`'s bytes
/// (`measured_boot::verify_in_manifest`, the check the progenitor runs on every load). Keeping the
/// trust root alive is a consequence of using it, not a `#[used]` that would seal a check nobody
/// makes, which is the inverse case `crates/sealed_pair`'s `BUGS` warns about.
///
/// **`None` means the archive does not have `name`**, or this boot has no archive at all (`x86_64`'s
/// QEMU bench leg attaches none). That is `measured_boot::verdict`'s split: an absent program is a
/// packaging fact the caller reports in its own words, while bytes the table will not vouch for are
/// a substitution, and those halt here with `MEASURED BOOT REFUSED` like [`require`]'s do.
///
/// Name: provisional, minted 2026-09-25 by milestone 563's lane, to sit beside [`require`] and
/// [`require_program_measurements`] as the third member of the family. calef names public functions.
// Called only by the boots that replace the hand-over; an ordinary boot measures through
// `user::boot_progenitor` and never reaches it.
#[cfg_attr(
    not(any(
        feature = "bench",
        feature = "soak_test",
        feature = "job_mix",
        feature = "disk_throughput"
    )),
    allow(dead_code)
)]
pub fn require_program(name: &str) -> Option<&'static [u8]> {
    let fs = nifefs::Fs::parse(crate::user::initrd()?).ok()?;
    // Halts unless the table is the one this kernel image was built against, so past this line the
    // table's word on `name` is the kernel's word.
    require_program_measurements(&fs);
    let bytes = fs.read(name)?;
    let table = fs
        .read(measured_boot::PROGRAM_MEASUREMENTS)
        .and_then(|t| core::str::from_utf8(t).ok())
        .unwrap_or("");
    match measured_boot::verify_in_manifest(table, name, bytes) {
        Ok(()) => Some(bytes),
        Err(measured_boot::VerifyError::Unmeasured) => {
            crate::println!();
            crate::println!(
                "  MEASURED BOOT REFUSED: the archive's measurement table has no entry for '{name}'"
            );
            crate::println!("  halting rather than entering a program nothing vouches for.");
            crate::arch::halt();
        }
        Err(measured_boot::VerifyError::Mismatch) => {
            crate::println!();
            crate::println!(
                "  MEASURED BOOT REFUSED: '{name}' is not what the archive's measurement table says"
            );
            crate::println!("    measured sha256 {}", Hex(&measured_boot::sha256(bytes)));
            crate::println!("  halting rather than entering a program nothing vouches for.");
            crate::arch::halt();
        }
    }
}

/// A digest as hex, for the diagnostics above. `Display` rather than a helper returning a string,
/// because there is no allocator here and the 64 characters have to live somewhere: they live in
/// this value's own frame while it is being formatted.
struct Hex<'a>(&'a measured_boot::Digest);

impl core::fmt::Display for Hex<'_> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        let text = measured_boot::hex(self.0);
        // SAFETY-free: `measured_boot::hex` emits only ASCII hex digits, so this cannot fail; the
        // fallback keeps the diagnostic printable rather than panicking inside a boot failure.
        f.write_str(core::str::from_utf8(&text).unwrap_or("<unprintable>"))
    }
}
