//! **The trust root: what init is allowed to be** (milestone 22 phase B.1, DECISIONS §22).
//!
//! The kernel loads exactly one program itself: the boot program, out of the initrd archive
//! (`"progenitor"` on every architecture, and `"builder"` for riscv64's boot tour). Everything else
//! is the progenitor's to load.
//! That one load used to be pure trust: whatever bytes sat at `/chosen/linux,initrd-start` got
//! parsed and entered. Since a compromised init can endow malicious children and deny the system it
//! was meant to start, and since milestone 16b closed the DMA window a device could have used to
//! rewrite the initrd *behind* a check, checking it is now both necessary and airtight.
//!
//! So: the build hashes the archive entry it packed and writes the digest into a manifest; the
//! kernel's `build.rs` compiles that manifest into [`TRUST_ROOT`] (below, generated into `OUT_DIR`);
//! and the boot path calls [`require`] before it enters userspace. The meaning is exactly "this
//! kernel image runs exactly this init," which needs no keys, no certificate chain, and no
//! signature-verification code inside the trusted computing base. The signature variant (update init
//! without rebuilding the kernel, at the cost of putting Ed25519 in the TCB) is recorded as a
//! follow-up in DECISIONS §22, not built.
//!
//! **It fails closed in both directions.** Wrong bytes halt, and a *missing* measurement halts too
//! (`measured_boot::VerifyError::Unmeasured`): a kernel built without the manifest has an empty trust root,
//! and an empty trust root vouches for nothing. That is deliberate. The failure mode of a measured
//! boot must never be "measure nothing and continue."
//!
//! See notes/trusted-init.md.

// `TRUST_ROOT`, generated by `kernel/build.rs` from `target/init-measure-<arch>.txt`: the digests of
// the boot programs this kernel image was built against. Empty if the build did not run the
// measurement step, which `require` treats as a refusal.
include!(concat!(env!("OUT_DIR"), "/trust_root.rs"));

/// The digest the trust root demands for the boot program `name`, if it names it.
// Test-only today: the boot path calls `require`, which decides and halts. These two are the same
// decision without the halt, which is what a test can actually assert on.
#[cfg_attr(not(test), allow(dead_code))]
pub fn expected(name: &str) -> Option<measured_boot::Digest> {
    measured_boot::expected(TRUST_ROOT, name)
}

/// Measure `bytes` against the trust root's entry for `name`. The decision function, separated from
/// the halt so tests can ask it what it thinks without ending the run.
#[cfg_attr(not(test), allow(dead_code))]
pub fn verify(name: &str, bytes: &[u8]) -> Result<(), measured_boot::VerifyError> {
    measured_boot::verify(TRUST_ROOT, name, bytes)
}

/// **Measure an archive entry, or halt.** Called with the entry's bytes immediately before the
/// kernel builds init's address space and drops to EL0/U-mode at its entry.
///
/// Two entries reach it: the boot program itself, and (since milestone 104) the measurement table
/// init loads everything else against, through [`require_program_measurements`]. The wording of the
/// diagnostics is deliberately about *entries* rather than *programs*, because one of them is not a
/// program.
///
/// A mismatch is not recoverable and must not be recovered from: there is no second init to fall
/// back to, and running the wrong one is precisely the thing being prevented. So this prints what it
/// expected, what it measured, and halts. Loudly, because a silent halt at boot is indistinguishable
/// from a hardware problem, and whoever hits this needs to know it was a *refusal*.
#[cfg_attr(feature = "bench", allow(dead_code))]
pub fn require(name: &str, bytes: &[u8]) {
    let measured = measured_boot::sha256(bytes);
    match measured_boot::verify_digest(TRUST_ROOT, name, &measured) {
        Ok(()) => {}
        Err(measured_boot::VerifyError::Unmeasured) => {
            crate::println!();
            crate::println!(
                "  MEASURED BOOT REFUSED: no measurement for the archive entry '{name}'"
            );
            crate::println!("    measured sha256 {}", Hex(&measured));
            crate::println!(
                "    this kernel image carries {} measurement(s); it was built without the",
                TRUST_ROOT.len()
            );
            crate::println!("    build's measurement step, so it can vouch for nothing.");
            crate::println!("  halting rather than handing the archive to init.");
            crate::arch::halt();
        }
        Err(measured_boot::VerifyError::Mismatch) => {
            crate::println!();
            crate::println!(
                "  MEASURED BOOT REFUSED: '{name}' is not what this kernel image was built against"
            );
            if let Some(want) = measured_boot::expected(TRUST_ROOT, name) {
                crate::println!("    expected sha256 {}", Hex(&want));
            }
            crate::println!("    measured sha256 {}", Hex(&measured));
            crate::println!("  halting rather than handing the archive to init.");
            crate::arch::halt();
        }
    }
}

/// **Vouch for the table init measures its own loads against** (milestone 104), which is the whole
/// of the kernel's part in extending the chain past init.
///
/// The kernel loads one program and measures it. Everything else in the archive is init's to load,
/// and until this existed those bytes were unchecked, so the chain of trust stopped at init's entry.
/// The fix belongs in userspace (init decides what to do about a mismatch, the same way §26's
/// supervisor decides what to do about a fault), and it needs exactly one thing from here: a table
/// init can trust as much as the kernel trusts init.
///
/// **Why the kernel measures a file it never reads.** init's own table cannot be compiled into init,
/// because init is *in* the archive it would be measuring; generating it would mean building
/// userspace twice with an invariant holding the chain up. So the build packs the table as an
/// ordinary archive entry, [`measured_boot::PROGRAM_MEASUREMENTS`], and this hashes it beside init.
/// Nothing here parses it or acts on it: the kernel gains one digest in its trust root and no
/// policy at all, which is the line DECISIONS §26 draws and notes/trusted-init.md's rejected
/// alternative (hashing the whole 14 MB archive in the kernel) crosses.
///
/// A **missing** table halts, for [`require`]'s reason one level down: an init that cannot vouch for
/// what it loads must not be handed the archive at all.
#[cfg_attr(feature = "bench", allow(dead_code))]
pub fn require_program_measurements(fs: &nifefs::Fs<'_>) {
    let name = measured_boot::PROGRAM_MEASUREMENTS;
    match fs.read(name) {
        Some(bytes) => require(name, bytes),
        None => {
            crate::println!();
            crate::println!("  MEASURED BOOT REFUSED: the archive carries no '{name}' table");
            crate::println!(
                "    init could not vouch for anything it loads, so it is not started."
            );
            crate::println!("  halting rather than entering an init that measures nothing.");
            crate::arch::halt();
        }
    }
}

/// A digest as hex, for the diagnostics above. `Display` rather than a helper returning a string,
/// because there is no allocator here and the 64 characters have to live somewhere: they live in
/// this value's own frame while it is being formatted.
struct Hex<'a>(&'a measured_boot::Digest);

impl core::fmt::Display for Hex<'_> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        let text = measured_boot::hex(self.0);
        // SAFETY-free: `measured_boot::hex` emits only ASCII hex digits, so this cannot fail; the
        // fallback keeps the diagnostic printable rather than panicking inside a boot failure.
        f.write_str(core::str::from_utf8(&text).unwrap_or("<unprintable>"))
    }
}
